from __future__ import annotations

import importlib.util
import json
from pathlib import Path
from typing import Any

import pytest

ROOT = Path(__file__).resolve().parents[1]
TOOL = ROOT / "tools" / "materialize_d03_code_capacity_four_sources.py"


def _module():
    spec = importlib.util.spec_from_file_location("d03_four_source_materializer_tested", TOOL)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _fake_records() -> list[dict[str, Any]]:
    sizes = [85_334, 82_023, 36_123, 31_724, 25_257, 53_050, 15_837, 7_599]
    families = [
        "github:pydantic/pydantic",
        "github:pydantic/pydantic",
        "github:pydantic/pydantic",
        "github:pydantic/pydantic",
        "code.scipy.project",
        "code.scipy.project",
        "github:pandas-dev/pandas",
        "github:fastapi/typer",
    ]
    return [
        {
            "schema_version": "test-only",
            "object_id": f"object-{index}",
            "authority_source_id": None,
            "source_family": family,
            "repository": "example/project",
            "commit": "a" * 40,
            "path": f"src/object_{index}.py",
            "git_blob_sha1": f"{index + 1:040x}",
            "raw_sha256": f"{index + 1:064x}",
            "utf8_bytes": size,
            "modality": "code",
            "normalization": "STRICT_UTF8_IDENTITY_PRESERVE_V1",
            "text": f"x_{index} = {index}\n",
        }
        for index, (size, family) in enumerate(zip(sizes, families, strict=True))
    ]


def test_repository_source_authorities_are_locally_well_formed() -> None:
    mod = _module()

    pydantic = mod._read_strict(ROOT / mod.PYDANTIC_CONFIG, context="Pydantic test")
    assert pydantic["source_family"] == "github:pydantic/pydantic"
    assert len(pydantic["decisions"]) == 4
    assert sum(row["size_bytes"] for row in pydantic["decisions"]) == 235_204

    scipy = mod.load_and_validate_source_authority(ROOT / mod.SCIPY_CONFIG)
    assert scipy["candidate_raw_bytes"] == 78_307
    assert scipy["canonical_credit_bytes"] == 0

    assert mod.pandas_source_authority.validate_pandas_source_authority_files(ROOT) == []
    assert mod.typer_source_authority.validate_typer_source_authority_files(ROOT) == []


@pytest.mark.parametrize(
    "raw",
    [
        b'{"a":1,"a":2}',
        b'{"a":NaN}',
        b'{"a":1e-9999}',
        b'{"a":' + b"9" * 65 + b"}",
    ],
)
def test_strict_json_refuses_ambiguous_or_unsafe_numbers(raw: bytes) -> None:
    mod = _module()
    with pytest.raises(mod.FourSourceMaterializationError):
        mod._strict_object(raw, context="test")


def test_verify_code_payload_binds_bytes_blob_sha_and_python() -> None:
    mod = _module()
    raw = b"def add(left, right):\n    return left + right\n"
    result = mod._verify_code_payload(
        raw,
        path="pkg/sample.py",
        expected_bytes=len(raw),
        expected_blob=mod._git_blob_sha1(raw),
        expected_sha256=mod._sha256(raw),
    )
    assert result == {"text": raw.decode(), "raw_sha256": mod._sha256(raw)}

    with pytest.raises(mod.FourSourceMaterializationError, match="byte count drift"):
        mod._verify_code_payload(
            raw,
            path="pkg/sample.py",
            expected_bytes=len(raw) + 1,
            expected_blob=mod._git_blob_sha1(raw),
        )

    with pytest.raises(mod.FourSourceMaterializationError, match="Git blob drift"):
        mod._verify_code_payload(
            raw,
            path="pkg/sample.py",
            expected_bytes=len(raw),
            expected_blob="0" * 40,
        )

    with pytest.raises(mod.FourSourceMaterializationError, match="SHA-256 drift"):
        mod._verify_code_payload(
            raw,
            path="pkg/sample.py",
            expected_bytes=len(raw),
            expected_blob=mod._git_blob_sha1(raw),
            expected_sha256="0" * 64,
        )


def test_verify_code_payload_refuses_secret_generated_invalid_utf8_and_bad_ast() -> None:
    mod = _module()
    bad_values = [
        (b'TOKEN = "sk-' + b"a" * 32 + b'"\n', "credential pattern"),
        (b"# generated by unit test\nx = 1\n", "generated-material marker"),
        (b"x = '\xff'\n", "strict UTF-8"),
        (b"def broken(:\n    pass\n", "AST parse"),
    ]
    for raw, message in bad_values:
        with pytest.raises(mod.FourSourceMaterializationError, match=message):
            mod._verify_code_payload(
                raw,
                path="pkg/sample.py",
                expected_bytes=len(raw),
                expected_blob=mod._git_blob_sha1(raw),
            )


def test_candidate_is_deterministic_and_enforces_exact_object_and_byte_floor() -> None:
    mod = _module()
    records = _fake_records()
    first = mod._render_candidate(records)
    second = mod._render_candidate(list(reversed(records)))
    assert first == second
    assert len(first.splitlines()) == 8
    assert sum(row["utf8_bytes"] for row in records) == mod.EXPECTED_RAW_BYTES

    too_few = records[:-1]
    with pytest.raises(mod.FourSourceMaterializationError, match="object count drift"):
        mod._render_candidate(too_few)

    wrong_total = [dict(row) for row in records]
    wrong_total[0]["utf8_bytes"] += 1
    with pytest.raises(mod.FourSourceMaterializationError, match="raw byte total drift"):
        mod._render_candidate(wrong_total)

    duplicate = [dict(row) for row in records]
    duplicate[1]["raw_sha256"] = duplicate[0]["raw_sha256"]
    with pytest.raises(mod.FourSourceMaterializationError, match="exact duplicate"):
        mod._render_candidate(duplicate)


def test_receipt_is_text_free_zero_credit_and_binds_candidate() -> None:
    mod = _module()
    records = _fake_records()
    candidate = mod._render_candidate(records)
    licenses = {
        "github:pydantic/pydantic": {"license_id": "MIT", "sha256": "1" * 64},
        "code.scipy.project": {"license_id": "BSD-3-Clause", "sha256": "2" * 64},
        "github:pandas-dev/pandas": {"license_id": "BSD-3-Clause", "sha256": "3" * 64},
        "github:fastapi/typer": {"license_id": "MIT", "sha256": "4" * 64},
    }
    receipt = mod._receipt(
        records,
        licenses,
        candidate=candidate,
        execution_head="a" * 40,
    )
    assert receipt["candidate_sha256"] == mod._sha256(candidate)
    assert receipt["materialized_object_count"] == 8
    assert receipt["materialized_raw_bytes"] == 336_947
    assert receipt["content_boundary"]["receipt_contains_raw_source_text"] is False
    truth = receipt["truth_boundary"]
    assert truth["canonical_capacity_credit_bytes"] == 0
    assert truth["authorized_optimized_target_exposure"] == 0
    assert truth["training_executed"] is False
    assert truth["final_test_outcomes_read"] is False
    assert truth["paid_compute_used"] is False

    core = dict(receipt)
    identity = core.pop("receipt_identity_sha256")
    assert identity == mod._sha256(mod._canonical(core))
    serialized = json.dumps(receipt, sort_keys=True)
    for record in records:
        assert record["text"] not in serialized


def test_materialize_composes_four_disjoint_sources_without_network(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    mod = _module()
    records = _fake_records()
    licenses = [
        {"license_id": "MIT", "sha256": "1" * 64},
        {"license_id": "BSD-3-Clause", "sha256": "2" * 64},
        {"license_id": "BSD-3-Clause", "sha256": "3" * 64},
        {"license_id": "MIT", "sha256": "4" * 64},
    ]

    monkeypatch.setattr(
        mod,
        "_capture_pydantic",
        lambda *_args, **_kwargs: (records[:4], licenses[0]),
    )
    monkeypatch.setattr(
        mod,
        "_materialize_scipy",
        lambda *_args, **_kwargs: (records[4:6], licenses[1]),
    )
    monkeypatch.setattr(
        mod,
        "_materialize_pandas",
        lambda *_args, **_kwargs: ([records[6]], licenses[2]),
    )
    monkeypatch.setattr(
        mod,
        "_materialize_typer",
        lambda *_args, **_kwargs: ([records[7]], licenses[3]),
    )

    candidate, receipt = mod.materialize(
        tmp_path,
        execution_head="b" * 40,
        fetch=lambda _url, _bound: (_ for _ in ()).throw(
            AssertionError("network should not be reached")
        ),
    )
    assert len(candidate.splitlines()) == 8
    assert receipt["execution_head_sha"] == "b" * 40
    assert receipt["candidate_sha256"] == mod._sha256(candidate)


def test_create_only_output_never_overwrites(tmp_path: Path) -> None:
    mod = _module()
    output = tmp_path / "candidate.jsonl"
    mod._write_create_only(output, b"first")
    assert output.read_bytes() == b"first"
    with pytest.raises(mod.FourSourceMaterializationError, match="refusing to overwrite"):
        mod._write_create_only(output, b"second")
    assert output.read_bytes() == b"first"
