"""NEXT100-055 bounded external-real SQLAlchemy code admission authority."""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import re
import subprocess
import urllib.request
from pathlib import Path
from typing import Any

SCHEMA = "12-6.next100-055-sqlalchemy-code-admission-report.v1"
MANIFEST_PATH = Path("configs/data/next100_055_sqlalchemy_code_rights_v1.json")
REPORT_NAME = "next100-055-sqlalchemy-code-admission.json"
BANNED_PARTS = frozenset({"vendor", "vendored", "third_party", "third-party", "node_modules", "dist", "build", "generated", "autogenerated", "gen", "site-packages", "__pycache__"})
GENERATED_MARKERS = ("do not edit", "auto-generated", "autogenerated", "generated by", "this file is generated", "automatically generated")
SECRET_PATTERNS = {
    "private_key": re.compile(rb"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    "github_token": re.compile(rb"\bgh[pousr]_[A-Za-z0-9_]{20,}\b"),
    "openai_key": re.compile(rb"\bsk-[A-Za-z0-9_-]{20,}\b"),
    "aws_access_key": re.compile(rb"\bAKIA[0-9A-Z]{16}\b"),
    "google_api_key": re.compile(rb"\bAIza[0-9A-Za-z_-]{30,}\b"),
    "slack_token": re.compile(rb"\bxox[baprs]-[0-9A-Za-z-]{10,}\b"),
}
SSN_PATTERN = re.compile(rb"\b\d{3}-\d{2}-\d{4}\b")
PAN_PATTERN = re.compile(rb"(?<!\d)(?:\d[ -]?){13,19}(?!\d)")
TOKEN_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*|\d+|[^\s]")


class AdmissionError(RuntimeError):
    pass


def _cjson(value: object) -> bytes:
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n").encode("utf-8")


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _git_blob_sha1(data: bytes) -> str:
    return hashlib.sha1(f"blob {len(data)}\0".encode("ascii") + data).hexdigest()


def _download(url: str, max_bytes: int = 400_000) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": "12-6-NEXT100-055-sqlalchemy/1"})
    with urllib.request.urlopen(request, timeout=30) as response:
        data = response.read(max_bytes + 1)
    if len(data) > max_bytes:
        raise AdmissionError(f"download exceeds {max_bytes}: {url}")
    return data


def _json(url: str, max_bytes: int = 400_000) -> dict[str, Any]:
    return json.loads(_download(url, max_bytes))


def _require_head(repo: Path, expected: str) -> None:
    actual = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo, text=True).strip()
    if actual != expected:
        raise AdmissionError(f"source head mismatch: {actual} != {expected}")


def load_manifest(repo: Path) -> dict[str, Any]:
    value = json.loads((repo / MANIFEST_PATH).read_text(encoding="utf-8"))
    if value.get("schema_version") != "12-6.next100-055-sqlalchemy-code-admission.v1":
        raise AdmissionError("manifest schema mismatch")
    if value.get("worker_id") != "NEXT100-055-CODE-SQLALCHEMY":
        raise AdmissionError("worker mismatch")
    if value["upstream"]["source_family"] != "github:sqlalchemy/sqlalchemy":
        raise AdmissionError("source family mismatch")
    selected = value["selected_files"]
    if len(selected) != 6 or len({x["path"] for x in selected}) != 6:
        raise AdmissionError("selected inventory must contain exactly six unique files")
    if sum(x["size_bytes"] for x in selected) != value["candidate_bytes"] or value["candidate_bytes"] != 831341:
        raise AdmissionError("candidate byte inventory mismatch")
    if value["selection_policy"]["generated_artifact_unique_capacity_credit"] != 0:
        raise AdmissionError("generated artifacts cannot count as unique capacity")
    uses = value["license_review"]["uses"]
    if uses["model_training"] != "ALLOWED" or uses["redistribution"] != "ALLOWED":
        raise AdmissionError("training/redistribution authority absent")
    boundary = value["evaluation_boundary"]
    if boundary["candidate_role"] != "TRAINING_ONLY" or boundary["evaluation_use_authorized"] is not False:
        raise AdmissionError("evaluation boundary mismatch")
    if boundary["selection_records_at_review"] or boundary["final_test_records_at_review"]:
        raise AdmissionError("code evaluation reservation not empty")
    return value


def _assert_human_authored_path(path: str, text: str) -> None:
    p = Path(path)
    if p.is_absolute() or ".." in p.parts:
        raise AdmissionError(f"unsafe path: {path}")
    if any(part.casefold() in BANNED_PARTS for part in p.parts):
        raise AdmissionError(f"generated/vendor/build path: {path}")
    if not path.startswith("lib/sqlalchemy/") or not path.endswith(".py"):
        raise AdmissionError(f"not first-party SQLAlchemy Python implementation: {path}")
    first = "\n".join(text.splitlines()[:40]).casefold()
    if any(marker in first for marker in GENERATED_MARKERS):
        raise AdmissionError(f"generated marker found: {path}")
    if "this module is part of sqlalchemy and is released under" not in first or "mit license" not in first:
        raise AdmissionError(f"first-party SQLAlchemy MIT header missing: {path}")


def _scan_secrets(data: bytes) -> list[str]:
    return [name for name, pattern in SECRET_PATTERNS.items() if pattern.search(data)]


def _luhn_valid(number: str) -> bool:
    digits = [int(ch) for ch in number]
    total = 0
    parity = len(digits) % 2
    for i, digit in enumerate(digits):
        if i % 2 == parity:
            digit *= 2
            if digit > 9:
                digit -= 9
        total += digit
    return total % 10 == 0


def _scan_privacy(data: bytes) -> list[str]:
    findings: list[str] = []
    if SSN_PATTERN.search(data):
        findings.append("us_ssn_like")
    for match in PAN_PATTERN.finditer(data):
        digits = re.sub(rb"\D", b"", match.group()).decode("ascii")
        if 13 <= len(digits) <= 19 and _luhn_valid(digits):
            findings.append("payment_pan_like")
            break
    return findings


def _shingles(text: str, n: int = 5) -> set[tuple[str, ...]]:
    tokens = TOKEN_RE.findall(text.casefold())
    if len(tokens) < n:
        return set()
    return {tuple(tokens[i:i+n]) for i in range(len(tokens) - n + 1)}


def _jaccard(a: str, b: str) -> float:
    left, right = _shingles(a), _shingles(b)
    if not left or not right:
        return 0.0
    return len(left & right) / len(left | right)


def _verify_upstream(manifest: dict[str, Any]) -> dict[str, Any]:
    upstream = manifest["upstream"]
    meta = _json("https://api.github.com/repos/sqlalchemy/sqlalchemy")
    if meta.get("html_url") != upstream["repository"] or meta.get("fork") is not False:
        raise AdmissionError("upstream repository identity drift")
    ref = _json(f"https://api.github.com/repos/sqlalchemy/sqlalchemy/git/ref/tags/{upstream['release_tag']}")
    if ref["object"]["type"] != "commit" or ref["object"]["sha"] != upstream["commit"]:
        raise AdmissionError("release tag target drift")
    commit = _json(f"https://api.github.com/repos/sqlalchemy/sqlalchemy/git/commits/{upstream['commit']}")
    if commit["tree"]["sha"] != upstream["tree_sha1"]:
        raise AdmissionError("release tree drift")
    return {"repository": upstream["repository"], "release_tag": upstream["release_tag"], "commit": upstream["commit"], "tree_sha1": upstream["tree_sha1"], "status": "PASS"}


def _verify_license(manifest: dict[str, Any], output: Path) -> dict[str, Any]:
    review = manifest["license_review"]
    raw = _download(review["license_url"], 10_000)
    if len(raw) != review["license_size_bytes"] or _git_blob_sha1(raw) != review["license_blob_sha1"]:
        raise AdmissionError("license immutable identity drift")
    text = raw.decode("utf-8")
    required = ("Permission is hereby granted, free of charge", "use, copy, modify, merge, publish, distribute, sublicense, and/or sell", "The above copyright notice and this permission notice shall be included", 'THE SOFTWARE IS PROVIDED "AS IS"')
    if not all(fragment in text for fragment in required):
        raise AdmissionError("MIT grant text drift")
    rights = output / "rights-evidence"
    rights.mkdir(parents=True, exist_ok=True)
    (rights / "LICENSE").write_bytes(raw)
    return {"license_id": "MIT", "license_blob_sha1": review["license_blob_sha1"], "license_sha256": _sha256(raw), "model_training": "ALLOWED", "redistribution": "ALLOWED_WITH_NOTICE", "condition": review["redistribution_conditions"], "status": "PASS"}


def _verify_candidate(manifest: dict[str, Any], item: dict[str, Any], output: Path) -> tuple[dict[str, Any], str]:
    commit, path = manifest["upstream"]["commit"], item["path"]
    raw = _download(f"https://raw.githubusercontent.com/sqlalchemy/sqlalchemy/{commit}/{path}")
    if len(raw) != item["size_bytes"] or _git_blob_sha1(raw) != item["blob_sha1"]:
        raise AdmissionError(f"{path}: immutable blob drift")
    if b"\0" in raw:
        raise AdmissionError(f"{path}: NUL byte")
    if findings := _scan_secrets(raw):
        raise AdmissionError(f"{path}: secret-like material {findings}")
    if findings := _scan_privacy(raw):
        raise AdmissionError(f"{path}: high-risk PII-like material {findings}")
    text = raw.decode("utf-8")
    if text.encode("utf-8") != raw:
        raise AdmissionError(f"{path}: UTF-8 identity drift")
    _assert_human_authored_path(path, text)
    ast.parse(text, filename=path)
    snap = output / "snapshots" / path
    snap.parent.mkdir(parents=True, exist_ok=True)
    snap.write_bytes(raw)
    return ({"path": path, "blob_sha1": item["blob_sha1"], "raw_sha256": _sha256(raw), "size_bytes": len(raw), "human_authored": "PASS", "generated_artifact": False, "parse": "PASS", "secret_scan": "PASS", "privacy_scan": "PASS"}, text)


def _verify_baseline(manifest: dict[str, Any]) -> list[tuple[dict[str, Any], str]]:
    result = []
    for item in manifest["terminal_code_registry_baseline"]["objects"]:
        raw = _download(item["raw_url"])
        if len(raw) != item["size_bytes"]:
            raise AdmissionError(f"baseline size drift: {item['source_id']}")
        if _git_blob_sha1(raw) != item["blob_sha1"] or _sha256(raw) != item["raw_sha256"]:
            raise AdmissionError(f"baseline identity drift: {item['source_id']}")
        result.append((item, raw.decode("utf-8")))
    return result


def _verify_evaluation(manifest: dict[str, Any]) -> dict[str, Any]:
    b = manifest["evaluation_boundary"]
    url = f"https://raw.githubusercontent.com/Oleksii-debug/12-6-ai./{b['head_at_review']}/{b['evidence_path']}"
    raw = _download(url, 40_000)
    if _git_blob_sha1(raw) != b["evidence_blob_sha1"]:
        raise AdmissionError("EVAL-322 evidence blob drift")
    evidence = json.loads(raw)
    unsigned = dict(evidence)
    expected = unsigned.pop("evidence_identity_sha256")
    if expected != b["evidence_identity_sha256"] or _sha256(_cjson(unsigned)) != expected:
        raise AdmissionError("EVAL-322 canonical identity mismatch")
    gate = evidence["code_gate"]
    if gate["verdict"] != "BLOCKED" or gate["selection_records"] != 0 or gate["final_test_records"] != 0:
        raise AdmissionError("EVAL-322 code boundary no longer empty at reviewed authority")
    if evidence["selection_validation"]["component_identities"]["code_records"] != 0 or evidence["final_test"]["code_included"] is not False:
        raise AdmissionError("reviewed evaluator includes code")
    return {"authority": b["authority"], "reviewed_head": b["head_at_review"], "selection_records": 0, "final_test_records": 0, "selected_blob_intersection_count": 0, "status": "PASS_NO_CODE_EVALUATION_RESERVATION_AT_REVIEWED_AUTHORITY"}


def _dedup(candidates: list[tuple[dict[str, Any], str]], baseline: list[tuple[dict[str, Any], str]], threshold: float) -> dict[str, Any]:
    exact: list[dict[str, Any]] = []
    near: list[dict[str, Any]] = []
    seen: dict[str, str] = {}
    for evidence, _ in candidates:
        digest = evidence["raw_sha256"]
        if digest in seen:
            exact.append({"left": seen[digest], "right": evidence["path"]})
        seen[digest] = evidence["path"]
    for item, _ in baseline:
        if item["raw_sha256"] in seen:
            exact.append({"left": seen[item["raw_sha256"]], "right": item["source_id"]})
    for i, (left, left_text) in enumerate(candidates):
        for right, right_text in candidates[i + 1:]:
            score = _jaccard(left_text, right_text)
            if score >= threshold:
                near.append({"left": left["path"], "right": right["path"], "jaccard": score, "scope": "within_sqlalchemy"})
        for item, text in baseline:
            score = _jaccard(left_text, text)
            if score >= threshold:
                near.append({"left": left["path"], "right": item["source_id"], "jaccard": score, "scope": "terminal_baseline"})
    if exact or near:
        raise AdmissionError(f"dedup rejection exact={exact} near={near}")
    return {"exact_duplicates": [], "near_duplicates_at_or_above_threshold": [], "near_threshold": threshold, "token_shingle_size": 5, "baseline_object_count": len(baseline), "status": "PASS"}


def run(repo: Path, output: Path, source_sha: str) -> dict[str, Any]:
    _require_head(repo, source_sha)
    manifest = load_manifest(repo)
    output.mkdir(parents=True, exist_ok=True)
    upstream = _verify_upstream(manifest)
    rights = _verify_license(manifest, output)
    evaluation = _verify_evaluation(manifest)
    candidates = [_verify_candidate(manifest, item, output) for item in manifest["selected_files"]]
    baseline = _verify_baseline(manifest)
    dedup = _dedup(candidates, baseline, manifest["verification"]["near_dedup"]["jaccard_threshold"])
    objects = [item for item, _ in candidates]
    snapshot = {"source_family": manifest["upstream"]["source_family"], "commit": manifest["upstream"]["commit"], "objects": [{"path": x["path"], "blob_sha1": x["blob_sha1"], "raw_sha256": x["raw_sha256"], "size_bytes": x["size_bytes"]} for x in objects], "total_bytes": sum(x["size_bytes"] for x in objects)}
    snapshot["identity_sha256"] = _sha256(_cjson(snapshot))
    report: dict[str, Any] = {
        "schema_version": SCHEMA,
        "worker_id": "NEXT100-055-CODE-SQLALCHEMY",
        "authority": "EXTERNAL_REAL_CODE_SOURCE_ADMISSION_LOCAL_FREE",
        "terminal": True,
        "verdict": "ADMIT_TRAINING_ONLY",
        "source_head": source_sha,
        "upstream_verification": upstream,
        "rights": rights,
        "selection": {"object_count": len(objects), "raw_bytes": sum(x["size_bytes"] for x in objects), "source_family_count": 1, "source_family": "github:sqlalchemy/sqlalchemy", "generated_artifact_unique_capacity_credit": 0},
        "objects": objects,
        "snapshot_manifest": snapshot,
        "privacy_secret_parse": {"strict_utf8_identity_all": True, "human_authored_all": True, "generated_artifacts_counted": False, "python_ast_parse_all": True, "secret_scan_all": "PASS", "privacy_scan_all": "PASS"},
        "deduplication": dedup,
        "source_family_decision": {"relationship_to_terminal_baseline": "INDEPENDENT_UPSTREAM_FAMILY", "decision": "ONE_SQLALCHEMY_FAMILY", "source_family": "github:sqlalchemy/sqlalchemy", "collapse_trigger": "Future exact/near duplicate or provenance lineage evidence must collapse/exclude affected objects."},
        "evaluation_boundary": evaluation,
        "terminal_code_registry_baseline": {"authority": manifest["terminal_code_registry_baseline"]["authority"], "head": manifest["terminal_code_registry_baseline"]["head"], "source_families": manifest["terminal_code_registry_baseline"]["source_families"], "object_count": len(baseline)},
        "execution_class": "LOCAL_FREE",
        "training_performed": False,
        "paid_compute_used": False,
    }
    report["manifest_identity_sha256"] = _sha256(_cjson(manifest))
    report["report_identity_sha256"] = _sha256(_cjson(report))
    (output / REPORT_NAME).write_bytes(_cjson(report))
    return report


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path("."))
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--source-sha", required=True)
    args = parser.parse_args()
    report = run(args.repo_root.resolve(), args.output_dir, args.source_sha)
    print(json.dumps({"verdict": report["verdict"], "report_identity_sha256": report["report_identity_sha256"], "snapshot_identity_sha256": report["snapshot_manifest"]["identity_sha256"], "objects": report["selection"]["object_count"], "bytes": report["selection"]["raw_bytes"]}, sort_keys=True))


if __name__ == "__main__":
    main()
