"""Rights-aware, format-preserving code-source intake for Base pretraining.

This module is deliberately an intake adapter, not a code-specific training path.
It preserves upstream UTF-8 source text exactly, delegates source-rights authority
to D03, and hands eligible code to the incumbent DATA-10 mixture contract.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import asdict, dataclass
from pathlib import PurePosixPath
from typing import Any, Iterable, Mapping, Sequence

CODE_CANDIDATE_SCHEMA = "12-6.code-source-candidate-registry.v1"
CODE_SAMPLE_MANIFEST_SCHEMA = "12-6.code-source-sample-manifest.v1"
CODE_PILOT_REPORT_SCHEMA = "12-6.code-source-pilot-report.v1"
NEAR_DEDUP_AUTHORITY = (
    "LOCAL_FREE_DIAGNOSTIC_ONLY_PRODUCTION_USES_D03_DATATROVE_MINHASH_0.10.0"
)

_LANGUAGE_BY_SUFFIX = {
    ".py": "Python",
    ".pyi": "Python",
    ".js": "JavaScript",
    ".mjs": "JavaScript",
    ".cjs": "JavaScript",
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
    ".rs": "Rust",
    ".go": "Go",
    ".java": "Java",
    ".kt": "Kotlin",
    ".kts": "Kotlin",
    ".c": "C",
    ".h": "C",
    ".cc": "C++",
    ".cpp": "C++",
    ".cxx": "C++",
    ".hpp": "C++",
    ".cs": "C#",
    ".rb": "Ruby",
    ".php": "PHP",
    ".swift": "Swift",
    ".scala": "Scala",
    ".sh": "Shell",
    ".bash": "Shell",
}
_REJECT_PATH_SEGMENTS = frozenset(
    {
        ".git",
        ".hg",
        ".svn",
        "node_modules",
        "vendor",
        "vendors",
        "third_party",
        "third-party",
        "dist",
        "build",
        "target",
        "site-packages",
        "__pycache__",
        "generated",
        "gen",
    }
)
_GENERATED_MARKERS = (
    "@generated",
    "do not edit",
    "do not modify",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "generated file",
)
_CODE_TOKEN_RE = re.compile(r"\w+|[^\s\w]", re.UNICODE)


class CodeSourceError(ValueError):
    """Fail-closed code-source intake error."""


def _canonical_json_bytes(value: Any) -> bytes:
    return (
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        + "\n"
    ).encode("utf-8")


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _require_text(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise CodeSourceError(f"{field} must be a non-empty string")
    return value


def _require_sha256(value: Any, field: str) -> str:
    text = _require_text(value, field)
    if len(text) != 64 or text != text.lower():
        raise CodeSourceError(f"{field} must be lowercase SHA-256")
    if any(char not in "0123456789abcdef" for char in text):
        raise CodeSourceError(f"{field} must be lowercase SHA-256")
    return text


def _require_git_sha(value: Any, field: str) -> str:
    text = _require_text(value, field)
    if len(text) != 40 or text != text.lower():
        raise CodeSourceError(f"{field} must be lowercase 40-hex Git SHA")
    if any(char not in "0123456789abcdef" for char in text):
        raise CodeSourceError(f"{field} must be lowercase 40-hex Git SHA")
    return text


def _safe_repo_path(value: str) -> str:
    if "\\" in value:
        raise CodeSourceError("repository paths must use POSIX separators")
    path = PurePosixPath(value)
    if path.is_absolute() or not path.parts or any(part in {"", ".", ".."} for part in path.parts):
        raise CodeSourceError("repository path must be normalized and relative")
    return path.as_posix()


@dataclass(frozen=True)
class LicenseObservation:
    spdx_id: str
    path: str
    git_blob_sha1: str
    text_sha256: str

    def __post_init__(self) -> None:
        _require_text(self.spdx_id, "license.spdx_id")
        _safe_repo_path(self.path)
        _require_git_sha(self.git_blob_sha1, "license.git_blob_sha1")
        _require_sha256(self.text_sha256, "license.text_sha256")


@dataclass(frozen=True)
class CodeSourceCandidate:
    source_id: str
    repository: str
    revision: str
    source_url: str
    d03_source_version: str
    license: LicenseObservation
    d03_rights_status: str = "REVIEW_REQUIRED"

    def __post_init__(self) -> None:
        _require_text(self.source_id, "source_id")
        _require_text(self.repository, "repository")
        _require_git_sha(self.revision, "revision")
        if self.d03_source_version != self.revision:
            raise CodeSourceError("d03_source_version must equal exact repository revision")
        if not self.source_url.startswith("https://github.com/"):
            raise CodeSourceError(
                "mechanical pilot source_url must be a GitHub HTTPS repository URL"
            )
        if self.d03_rights_status != "REVIEW_REQUIRED":
            raise CodeSourceError(
                "candidate registry is observational only; D03 approval must not be encoded here"
            )


@dataclass(frozen=True)
class CodeFileRecord:
    record_id: str
    source_id: str
    repository: str
    revision: str
    path: str
    language: str
    source_sha256: str
    source_size_bytes: int
    git_blob_sha1: str
    license_spdx_id: str
    license_path: str
    license_text_sha256: str
    text: str
    mechanically_accepted: bool
    rejection_reason: str | None
    rights_status: str
    training_eligible: bool

    def manifest_entry(self) -> dict[str, Any]:
        entry = asdict(self)
        entry.pop("text")
        entry["text_preserved_exactly"] = True
        entry["comments_stripped"] = False
        entry["normalization"] = "NONE_STRICT_UTF8_IDENTITY"
        return entry


@dataclass(frozen=True)
class FileFilterDecision:
    accepted: bool
    language: str | None
    reason: str | None


def strict_utf8_identity(payload: bytes) -> str:
    """Decode strict UTF-8 without changing one source byte.

    No NFKC/NFC, newline conversion, trimming, indentation changes, or comment
    stripping is performed. Re-encoding must reproduce the exact input bytes.
    """

    if not isinstance(payload, bytes):
        raise TypeError("payload must be bytes")
    if b"\x00" in payload:
        raise CodeSourceError("NUL byte indicates binary/non-text content")
    try:
        text = payload.decode("utf-8", errors="strict")
    except UnicodeDecodeError as exc:
        raise CodeSourceError("source is not strict UTF-8") from exc
    if text.encode("utf-8", errors="strict") != payload:
        raise CodeSourceError("strict UTF-8 identity round trip failed")
    return text


def language_for_path(path: str) -> str | None:
    safe = _safe_repo_path(path)
    lower = safe.lower()
    for suffix, language in sorted(_LANGUAGE_BY_SUFFIX.items(), key=lambda item: -len(item[0])):
        if lower.endswith(suffix):
            return language
    return None


def filter_code_file(path: str, payload: bytes) -> FileFilterDecision:
    """Conservatively reject likely binary/generated/vendor/minified artifacts."""

    safe = _safe_repo_path(path)
    parts = {part.casefold() for part in PurePosixPath(safe).parts}
    blocked = sorted(parts & _REJECT_PATH_SEGMENTS)
    if blocked:
        return FileFilterDecision(False, None, f"blocked_path_segment:{blocked[0]}")
    name = PurePosixPath(safe).name.casefold()
    if ".min." in name or name.endswith(".min"):
        return FileFilterDecision(False, None, "minified_filename")

    language = language_for_path(safe)
    if language is None:
        return FileFilterDecision(False, None, "unsupported_code_extension")

    try:
        text = strict_utf8_identity(payload)
    except CodeSourceError as exc:
        return FileFilterDecision(False, language, str(exc))

    prefix = text[:4096].casefold()
    if any(marker in prefix for marker in _GENERATED_MARKERS):
        return FileFilterDecision(False, language, "generated_marker")

    controls = sum(
        1
        for char in text
        if ord(char) < 32 and char not in {"\n", "\r", "\t", "\f"}
    )
    if controls > max(2, len(text) // 1000):
        return FileFilterDecision(False, language, "excess_control_characters")

    lines = text.splitlines()
    longest_line = max((len(line) for line in lines), default=0)
    if len(payload) >= 512 and len(lines) <= 2 and longest_line > 1000:
        return FileFilterDecision(False, language, "likely_minified_long_line")
    return FileFilterDecision(True, language, None)


def stable_record_id(repository: str, revision: str, path: str) -> str:
    repo = _require_text(repository, "repository")
    rev = _require_git_sha(revision, "revision")
    safe = _safe_repo_path(path)
    return "code:" + _sha256(f"{repo}\0{rev}\0{safe}".encode("utf-8"))


def evaluate_d03_rights(
    candidate: CodeSourceCandidate,
    registry: Mapping[str, Any],
) -> tuple[str, bool]:
    """Delegate canonical training permission to the incumbent D03 registry."""

    from twelve_six.data.external_sources import (
        ExternalDataContractError,
        validate_external_source_registry,
    )

    sources = validate_external_source_registry(registry)
    match = next(
        (
            source
            for source in sources
            if source.source_id == candidate.source_id
            and source.source_version == candidate.d03_source_version
        ),
        None,
    )
    if match is None:
        return "BLOCKED_NOT_IN_D03_APPROVED_REGISTRY", False
    try:
        match.assert_training_eligible()
    except ExternalDataContractError as exc:
        return f"BLOCKED_D03_RIGHTS:{type(exc).__name__}", False
    if match.rights.license_id != candidate.license.spdx_id:
        return "BLOCKED_LICENSE_ID_MISMATCH", False
    return "APPROVED_FOR_TRAINING", True


def ingest_code_file(
    candidate: CodeSourceCandidate,
    *,
    path: str,
    git_blob_sha1: str,
    payload: bytes,
    rights_status: str,
    training_eligible: bool,
) -> CodeFileRecord:
    safe = _safe_repo_path(path)
    blob = _require_git_sha(git_blob_sha1, "git_blob_sha1")
    decision = filter_code_file(safe, payload)
    text = strict_utf8_identity(payload) if decision.accepted else ""
    return CodeFileRecord(
        record_id=stable_record_id(candidate.repository, candidate.revision, safe),
        source_id=candidate.source_id,
        repository=candidate.repository,
        revision=candidate.revision,
        path=safe,
        language=decision.language or "unknown",
        source_sha256=_sha256(payload),
        source_size_bytes=len(payload),
        git_blob_sha1=blob,
        license_spdx_id=candidate.license.spdx_id,
        license_path=candidate.license.path,
        license_text_sha256=candidate.license.text_sha256,
        text=text,
        mechanically_accepted=decision.accepted,
        rejection_reason=decision.reason,
        rights_status=rights_status,
        training_eligible=bool(training_eligible and decision.accepted),
    )


def exact_duplicate_analysis(records: Sequence[CodeFileRecord]) -> dict[str, Any]:
    """Report exact content duplicates using the D03 content SHA identity."""

    by_hash: dict[str, list[str]] = {}
    for record in records:
        if not record.mechanically_accepted:
            continue
        by_hash.setdefault(record.source_sha256, []).append(record.record_id)
    groups = [sorted(ids) for ids in by_hash.values() if len(ids) > 1]
    groups.sort()
    return {
        "exact_key": "source_sha256",
        "accepted_records_checked": sum(record.mechanically_accepted for record in records),
        "duplicate_groups": groups,
        "duplicate_group_count": len(groups),
        "duplicate_record_count": sum(len(group) for group in groups),
        "production_scale_contract": "D03_SQLiteExactDedupIndex/content_sha256",
    }


def _token_shingles(text: str, width: int = 5) -> frozenset[tuple[str, ...]]:
    tokens = _CODE_TOKEN_RE.findall(text)
    if not tokens:
        return frozenset()
    if len(tokens) <= width:
        return frozenset({tuple(tokens)})
    return frozenset(
        tuple(tokens[index : index + width])
        for index in range(len(tokens) - width + 1)
    )


def near_duplicate_analysis(
    records: Sequence[CodeFileRecord], *, threshold: float = 0.85
) -> dict[str, Any]:
    """Bounded pilot diagnostic; production near-dedup remains DataTrove MinHash."""

    if not 0.0 < threshold <= 1.0:
        raise CodeSourceError("near duplicate threshold must be in (0, 1]")
    accepted = [record for record in records if record.mechanically_accepted]
    shingles = {record.record_id: _token_shingles(record.text) for record in accepted}
    pairs: list[dict[str, Any]] = []
    for left_index, left in enumerate(accepted):
        for right in accepted[left_index + 1 :]:
            a = shingles[left.record_id]
            b = shingles[right.record_id]
            union = a | b
            similarity = len(a & b) / len(union) if union else 1.0
            if similarity >= threshold:
                pairs.append(
                    {
                        "left_record_id": left.record_id,
                        "right_record_id": right.record_id,
                        "jaccard_5_token_shingles": similarity,
                    }
                )
    pairs.sort(key=lambda item: (item["left_record_id"], item["right_record_id"]))
    return {
        "authority": NEAR_DEDUP_AUTHORITY,
        "threshold": threshold,
        "shingle_width_tokens": 5,
        "pairs": pairs,
        "pair_count": len(pairs),
        "semantic_cleanliness_claimed": False,
    }


def build_sample_manifest(records: Iterable[CodeFileRecord]) -> dict[str, Any]:
    ordered = sorted(records, key=lambda item: (item.repository, item.revision, item.path))
    core = {
        "schema_version": CODE_SAMPLE_MANIFEST_SCHEMA,
        "format_preservation": {
            "strict_utf8": True,
            "unicode_normalization": "NONE",
            "newline_conversion": False,
            "trim": False,
            "comments_stripped": False,
        },
        "records": [record.manifest_entry() for record in ordered],
    }
    return {**core, "manifest_sha256": _sha256(_canonical_json_bytes(core))}


def code_mixture_stratum(manifest_sha256: str):
    """Return the incumbent DATA-10 code stratum; no model behavior changes."""

    from twelve_six.data.multilingual_pretraining import MixtureStratum

    return MixtureStratum("code", _require_sha256(manifest_sha256, "manifest_sha256"), 20)
