"""Identity-preserving normalization and admission checks for source code.

Code is not natural text. This module deliberately performs no Unicode
normalization, newline rewriting, whitespace folding, indentation changes, or
semantic rewrites. Accepted UTF-8 source is returned byte-for-byte identical.
"""

from __future__ import annotations

import hashlib
import re
import unicodedata
from dataclasses import asdict, dataclass
from pathlib import PurePosixPath
from typing import Any

CODE_NORMALIZATION_SCHEMA = "12-6.code-normalization-evidence.v1"
CODE_NORMALIZATION_POLICY = "STRICT_UTF8_IDENTITY_PRESERVE_V1"
IDENTITY_REASON = "identity_utf8_source_preserved"

_GENERATED_MARKERS = (
    re.compile(r"(?i)\bcode generated\b.{0,120}\bdo not edit\b"),
    re.compile(r"(?i)<auto-generated(?:\s|>)"),
    re.compile(r"(?i)\bautomatically generated\b"),
    re.compile(r"(?i)\bthis file (?:is|was) generated\b"),
    re.compile(r"(?i)(?:^|\s)@generated(?:\s|$)"),
)
_MINIFIED_SUFFIXES = (".min.js", ".min.mjs", ".min.cjs", ".min.ts", ".min.tsx")
_MINIFIED_LANGUAGES = frozenset({"javascript", "js", "typescript", "ts", "tsx", "jsx"})
_ALLOWED_CONTROLS = frozenset({"\t", "\n", "\r", "\f"})


class CodeNormalizationError(ValueError):
    """Fail-closed code admission error carrying a machine-readable reason."""

    def __init__(self, reason: str, message: str) -> None:
        super().__init__(message)
        self.reason = reason


@dataclass(frozen=True)
class CodeStructure:
    codepoints: int
    utf8_bytes: int
    tabs: int
    crlf_newlines: int
    lf_newlines: int
    cr_newlines: int
    line_continuations: int
    longest_line_codepoints: int


@dataclass(frozen=True)
class CodeNormalizationEvidence:
    schema_version: str
    policy: str
    language: str
    path: str | None
    source_sha256: str
    normalized_sha256: str
    source_utf8_bytes: int
    normalized_utf8_bytes: int
    transformations: tuple[str, ...]
    reasons: tuple[str, ...]
    structure: CodeStructure

    def manifest(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class MarkdownFencedCodeBlock:
    fence: str
    info: str
    body: str


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _structure(text: str) -> CodeStructure:
    crlf = text.count("\r\n")
    lf = text.count("\n") - crlf
    cr = text.count("\r") - crlf
    lines = re.split(r"\r\n|\n|\r", text)
    longest = max((len(line) for line in lines), default=0)
    continuations = len(re.findall(r"\\(?:\r\n|\n|\r)", text))
    payload = text.encode("utf-8", errors="strict")
    return CodeStructure(
        codepoints=len(text),
        utf8_bytes=len(payload),
        tabs=text.count("\t"),
        crlf_newlines=crlf,
        lf_newlines=lf,
        cr_newlines=cr,
        line_continuations=continuations,
        longest_line_codepoints=longest,
    )


def _validate_textual_code(text: str) -> bytes:
    if not isinstance(text, str):
        raise TypeError("code text must be str")
    if not text or not text.strip():
        raise CodeNormalizationError("empty_code", "code source is empty or whitespace-only")
    if "\ufffd" in text:
        raise CodeNormalizationError(
            "replacement_character",
            "code source contains replacement character U+FFFD",
        )
    if any(0xD800 <= ord(char) <= 0xDFFF for char in text):
        raise CodeNormalizationError("surrogate_codepoint", "code source contains a surrogate")
    try:
        payload = text.encode("utf-8", errors="strict")
    except UnicodeEncodeError as exc:
        raise CodeNormalizationError("invalid_utf8_scalar", "code is not strict UTF-8") from exc
    if b"\x00" in payload:
        raise CodeNormalizationError("binary_nul", "code source contains NUL bytes")
    disallowed = [
        char
        for char in text
        if unicodedata.category(char) == "Cc" and char not in _ALLOWED_CONTROLS
    ]
    if disallowed:
        codepoint = ord(disallowed[0])
        raise CodeNormalizationError(
            "binary_control_character",
            f"code source contains disallowed control U+{codepoint:04X}",
        )
    return payload


def _path_is_explicitly_generated(path: str | None) -> bool:
    if not path:
        return False
    parts = [part.casefold() for part in PurePosixPath(path.replace("\\", "/")).parts]
    return any(
        part in {"generated", "generated-src", "generated_sources", "genfiles"}
        or part.startswith("generated.")
        for part in parts
    )


def _looks_explicitly_generated(text: str) -> bool:
    header = text[:8192]
    return any(pattern.search(header) is not None for pattern in _GENERATED_MARKERS)


def _path_is_minified(path: str | None) -> bool:
    if not path:
        return False
    lowered = path.casefold()
    return any(lowered.endswith(suffix) for suffix in _MINIFIED_SUFFIXES)


def _looks_extremely_minified(text: str, language: str) -> bool:
    if language.casefold() not in _MINIFIED_LANGUAGES or len(text) < 4000:
        return False
    structure = _structure(text)
    if structure.crlf_newlines + structure.lf_newlines + structure.cr_newlines > 1:
        return False
    visible = [char for char in text if not char.isspace()]
    if not visible:
        return False
    whitespace_ratio = sum(char.isspace() for char in text) / len(text)
    punctuation_ratio = sum(
        unicodedata.category(char).startswith(("P", "S")) for char in visible
    ) / len(visible)
    return (
        structure.longest_line_codepoints >= 4000
        and whitespace_ratio < 0.08
        and punctuation_ratio >= 0.15
    )


def normalize_code_text(
    text: str,
    *,
    language: str = "unknown",
    path: str | None = None,
) -> tuple[str, CodeNormalizationEvidence]:
    """Validate source code and return it exactly unchanged.

    This function is intentionally an identity transform. Rejection is used
    instead of repair whenever the input looks binary, generated, or minified.
    """
    payload = _validate_textual_code(text)
    if _path_is_explicitly_generated(path) or _looks_explicitly_generated(text):
        raise CodeNormalizationError(
            "generated_material",
            "code source has an explicit generated-material marker",
        )
    if _path_is_minified(path) or _looks_extremely_minified(text, language):
        raise CodeNormalizationError(
            "minified_material",
            "code source has an explicit or conservative minified-material signal",
        )

    digest = _sha256(payload)
    evidence = CodeNormalizationEvidence(
        schema_version=CODE_NORMALIZATION_SCHEMA,
        policy=CODE_NORMALIZATION_POLICY,
        language=language,
        path=path,
        source_sha256=digest,
        normalized_sha256=digest,
        source_utf8_bytes=len(payload),
        normalized_utf8_bytes=len(payload),
        transformations=(),
        reasons=(IDENTITY_REASON,),
        structure=_structure(text),
    )
    return text, evidence


def decode_code_bytes(
    payload: bytes,
    *,
    language: str = "unknown",
    path: str | None = None,
) -> tuple[str, CodeNormalizationEvidence]:
    """Strictly decode UTF-8 source bytes, then apply identity code admission."""
    if not isinstance(payload, bytes):
        raise TypeError("code payload must be bytes")
    try:
        text = payload.decode("utf-8", errors="strict")
    except UnicodeDecodeError as exc:
        raise CodeNormalizationError(
            "binary_invalid_utf8",
            "code payload is not valid UTF-8",
        ) from exc
    normalized, evidence = normalize_code_text(text, language=language, path=path)
    if normalized.encode("utf-8") != payload:
        raise CodeNormalizationError(
            "source_byte_roundtrip_mismatch",
            "strict UTF-8 decode/encode did not reproduce source bytes",
        )
    return normalized, evidence


def extract_markdown_fenced_code(text: str) -> tuple[MarkdownFencedCodeBlock, ...]:
    """Extract fenced Markdown bodies without normalizing their contents."""
    lines = text.splitlines(keepends=True)
    blocks: list[MarkdownFencedCodeBlock] = []
    index = 0
    while index < len(lines):
        match = re.match(r"^[ \t]{0,3}(`{3,}|~{3,})([^\r\n]*)", lines[index])
        if match is None:
            index += 1
            continue
        fence = match.group(1)
        info = match.group(2).strip()
        fence_char = re.escape(fence[0])
        close = re.compile(rf"^[ \t]{{0,3}}{fence_char}{{{len(fence)},}}[ \t]*(?:\r?\n)?$")
        body_start = index + 1
        cursor = body_start
        while cursor < len(lines) and close.match(lines[cursor]) is None:
            cursor += 1
        if cursor >= len(lines):
            index += 1
            continue
        blocks.append(
            MarkdownFencedCodeBlock(
                fence=fence,
                info=info,
                body="".join(lines[body_start:cursor]),
            )
        )
        index = cursor + 1
    return tuple(blocks)
