#!/usr/bin/env python3
"""Execution-only physical check of four bounded D03 code-source authorities."""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import math
import os
import re
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any

MAX_BYTES = 1_048_576
MAX_INT_DIGITS = 64
EXPECTED_BYTES = 336_947
EXPECTED_OBJECTS = 8
EXPECTED_FAMILIES = 4

CONFIGS = {
    "pydantic": Path("configs/data/next100_048_pydantic_code_rights_v1.json"),
    "pandas": Path("configs/data/next100_050_pandas_source_authority_v2.json"),
    "typer": Path("configs/data/next100_052_typer_source_authority_v2.json"),
    "scipy": Path("configs/data/scipy_v118_source_authority_v1.json"),
}
EXPECTED_CONFIG_BLOBS = {
    "pydantic": "504ef934145ed0711743f781dc9f47b07ad7accd",
    "pandas": "a97ccc1fcf097970abc84218e0fbd8088fa32887",
    "typer": "fc9168f2752d46fae76092999f449f0897fe0ca7",
    "scipy": "8bd1b020e324d33fdbcdda8619fbae7e73224d7e",
}

SECRET_PATTERNS = (
    re.compile(rb"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(rb"\bgh[pousr]_[A-Za-z0-9_]{20,}\b"),
    re.compile(rb"\bsk-[A-Za-z0-9_-]{20,}\b"),
    re.compile(rb"\bAKIA[0-9A-Z]{16}\b"),
)
GENERATED_PATTERNS = (
    re.compile(r"(?i)\bcode generated\b.{0,120}\bdo not edit\b"),
    re.compile(r"(?i)<auto-generated(?:\s|>)"),
    re.compile(r"(?i)\bautomatically generated\b"),
)


class MaterializationError(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise MaterializationError(message)


def sha256(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def git_blob_sha1(raw: bytes) -> str:
    return hashlib.sha1(  # noqa: S324 - exact Git object identity
        f"blob {len(raw)}\0".encode("ascii") + raw
    ).hexdigest()


def canonical(value: Any) -> bytes:
    return (
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        + "\n"
    ).encode("utf-8")


def _object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise MaterializationError("duplicate JSON member")
        result[key] = value
    return result


def _constant(value: str) -> None:
    raise MaterializationError(f"non-finite JSON constant: {value}")


def _float(value: str) -> float:
    parsed = float(value)
    if not math.isfinite(parsed):
        raise MaterializationError("non-finite JSON number")
    significand = value.split("e", 1)[0].split("E", 1)[0]
    if parsed == 0.0 and any(ch in "123456789" for ch in significand):
        raise MaterializationError("JSON float underflowed to zero")
    return parsed


def _int(value: str) -> int:
    if len(value.removeprefix("-")) > MAX_INT_DIGITS:
        raise MaterializationError("JSON integer exceeds 64 digits")
    return int(value)


def strict_json(raw: bytes, label: str) -> dict[str, Any]:
    require(len(raw) <= MAX_BYTES, f"{label}: byte limit exceeded")
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise MaterializationError(f"{label}: invalid UTF-8") from exc
    try:
        value = json.loads(
            text,
            object_pairs_hook=_object,
            parse_constant=_constant,
            parse_float=_float,
            parse_int=_int,
        )
    except json.JSONDecodeError as exc:
        raise MaterializationError(f"{label}: invalid JSON") from exc
    except RecursionError as exc:
        raise MaterializationError(f"{label}: nesting limit exceeded") from exc
    require(type(value) is dict, f"{label}: root is not object")
    return value


def load_config(root: Path, name: str) -> dict[str, Any]:
    path = root / CONFIGS[name]
    try:
        raw = path.read_bytes()
    except OSError as exc:
        raise MaterializationError(f"{name}: cannot read authority config") from exc
    require(
        git_blob_sha1(raw) == EXPECTED_CONFIG_BLOBS[name],
        f"{name}: current-main authority config blob drift",
    )
    return strict_json(raw, CONFIGS[name].as_posix())


def headers(url: str) -> dict[str, str]:
    result = {"User-Agent": "12-6-ai-d03-four-code-physical/1.0"}
    if urllib.parse.urlparse(url).hostname == "api.github.com":
        token = os.environ.get("GITHUB_TOKEN")
        if token:
            result.update(
                {
                    "Authorization": f"Bearer {token}",
                    "Accept": "application/vnd.github+json",
                    "X-GitHub-Api-Version": "2022-11-28",
                }
            )
    return result


def download(url: str, max_bytes: int = 400_000) -> bytes:
    request = urllib.request.Request(url, headers=headers(url))
    try:
        with urllib.request.urlopen(request, timeout=45) as response:
            raw = response.read(max_bytes + 1)
    except Exception as exc:
        raise MaterializationError("bounded exact-source download failed") from exc
    require(len(raw) <= max_bytes, "bounded exact-source download exceeded limit")
    return raw


def api_json(url: str) -> dict[str, Any]:
    return strict_json(download(url, MAX_BYTES), "GitHub API")


def code_evidence(
    raw: bytes,
    *,
    family: str,
    source_id: str,
    path: str,
    size: Any,
    blob: Any,
    digest: str | None = None,
) -> dict[str, Any]:
    require(type(size) is int and size > 0, f"{source_id}: invalid size authority")
    require(type(blob) is str and len(blob) == 40, f"{source_id}: invalid blob authority")
    require(len(raw) == size, f"{source_id}: byte count drift")
    require(git_blob_sha1(raw) == blob, f"{source_id}: Git blob drift")
    observed = sha256(raw)
    if digest is not None:
        require(observed == digest, f"{source_id}: SHA-256 drift")
    require(b"\x00" not in raw, f"{source_id}: NUL byte")
    require(
        not any(pattern.search(raw) for pattern in SECRET_PATTERNS),
        f"{source_id}: credential-like bytes detected",
    )
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise MaterializationError(f"{source_id}: invalid UTF-8") from exc
    require("\ufffd" not in text, f"{source_id}: replacement character")
    require(
        not any(0xD800 <= ord(ch) <= 0xDFFF for ch in text),
        f"{source_id}: surrogate code point",
    )
    require(
        not any(pattern.search(text) for pattern in GENERATED_PATTERNS),
        f"{source_id}: generated-material marker",
    )
    try:
        tree = ast.parse(text, filename=path)
        compile(tree, path, "exec", dont_inherit=True)
    except (SyntaxError, TypeError, ValueError) as exc:
        raise MaterializationError(f"{source_id}: syntax/compile failure") from exc
    return {
        "family": family,
        "source_id": source_id,
        "path": path,
        "raw_bytes": size,
        "git_blob_sha1": blob,
        "sha256": observed,
        "syntax": "PASS",
        "secret_privacy": "PASS_BOUNDED_SCAN",
        "generated_material": False,
    }


def license_evidence(
    raw: bytes,
    *,
    family: str,
    path: str,
    blob: str,
    digest: str | None = None,
    phrases: tuple[str, ...] = (),
) -> dict[str, Any]:
    require(git_blob_sha1(raw) == blob, f"{family}: license Git blob drift")
    observed = sha256(raw)
    if digest is not None:
        require(observed == digest, f"{family}: license SHA-256 drift")
    try:
        text = " ".join(raw.decode("utf-8").split()).casefold()
    except UnicodeDecodeError as exc:
        raise MaterializationError(f"{family}: license invalid UTF-8") from exc
    for phrase in phrases:
        require(phrase.casefold() in text, f"{family}: license phrase missing")
    return {
        "family": family,
        "path": path,
        "raw_bytes": len(raw),
        "git_blob_sha1": blob,
        "sha256": observed,
    }


def pydantic_materialization(config: dict[str, Any]) -> tuple[list[dict[str, Any]], Any]:
    family = "github:pydantic/pydantic"
    require(config.get("source_family") == family, "Pydantic family drift")
    commit = config.get("upstream_commit")
    rows = config.get("decisions")
    require(type(commit) is str and len(commit) == 40, "Pydantic commit drift")
    require(type(rows) is list and len(rows) == 4, "Pydantic object set drift")
    objects = []
    for row in rows:
        require(type(row) is dict, "Pydantic object authority invalid")
        require(row.get("commit") == commit, "Pydantic object commit drift")
        require(row.get("capacity_counted") is True, "Pydantic capacity flag drift")
        objects.append(
            code_evidence(
                download(str(row.get("raw_url"))),
                family=family,
                source_id=str(row.get("source_id")),
                path=str(row.get("path")),
                size=row.get("size_bytes"),
                blob=str(row.get("blob_sha1")),
            )
        )
    lic = config.get("license")
    require(type(lic) is dict, "Pydantic license authority missing")
    license_row = license_evidence(
        download(str(lic.get("url")), 100_000),
        family=family,
        path=str(lic.get("path")),
        blob=str(lic.get("blob_sha1")),
        phrases=(
            "deal in the Software without restriction",
            "copyright notice and this permission notice shall be included",
        ),
    )
    return objects, license_row


def single_materialization(
    config: dict[str, Any],
    label: str,
) -> tuple[list[dict[str, Any]], Any]:
    source = config.get("bounded_source")
    lic = config.get("license")
    require(type(source) is dict and type(lic) is dict, f"{label}: authority missing")
    repo = source.get("repository")
    commit = source.get("commit")
    path = source.get("path")
    require(
        all(type(item) is str and item for item in (repo, commit, path)),
        f"{label}: source identity drift",
    )
    family = str(source.get("source_family"))
    raw = download(f"https://raw.githubusercontent.com/{repo}/{commit}/{path}")
    source_row = code_evidence(
        raw,
        family=family,
        source_id=str(source.get("source_id")),
        path=str(path),
        size=source.get("size_bytes"),
        blob=str(source.get("git_blob_sha1")),
        digest=str(source.get("raw_sha256")),
    )
    license_path = lic.get("path")
    require(type(license_path) is str and license_path, f"{label}: license path drift")
    license_raw = download(
        f"https://raw.githubusercontent.com/{repo}/{commit}/{license_path}",
        100_000,
    )
    license_row = license_evidence(
        license_raw,
        family=family,
        path=license_path,
        blob=str(lic.get("git_blob_sha1")),
        digest=str(lic.get("sha256")),
    )
    return [source_row], license_row


def scipy_license_blobs(config: dict[str, Any]) -> dict[str, str]:
    upstream = config.get("upstream")
    require(type(upstream) is dict, "SciPy upstream authority missing")
    commit = upstream.get("commit_sha")
    tree_sha = upstream.get("tree_sha")
    require(type(commit) is str and len(commit) == 40, "SciPy commit drift")
    require(type(tree_sha) is str and len(tree_sha) == 40, "SciPy tree drift")
    commit_row = api_json(
        f"https://api.github.com/repos/scipy/scipy/git/commits/{commit}"
    )
    tree = commit_row.get("tree")
    require(type(tree) is dict and tree.get("sha") == tree_sha, "SciPy tree drift")
    tree_row = api_json(
        f"https://api.github.com/repos/scipy/scipy/git/trees/{tree_sha}"
    )
    entries = tree_row.get("tree")
    require(type(entries) is list, "SciPy root tree missing")
    required = {"LICENSE.txt", "LICENSES_bundled.txt"}
    found: dict[str, str] = {}
    for row in entries:
        if type(row) is not dict or row.get("path") not in required:
            continue
        require(row.get("type") == "blob", "SciPy license entry not a blob")
        blob = row.get("sha")
        require(type(blob) is str and len(blob) == 40, "SciPy license blob invalid")
        found[str(row["path"])] = blob
    require(set(found) == required, "SciPy pinned tree missing licenses")
    return found


def scipy_materialization(config: dict[str, Any]) -> tuple[list[dict[str, Any]], Any]:
    family = "code.scipy.project"
    require(config.get("source_family") == family, "SciPy family drift")
    upstream = config.get("upstream")
    rows = config.get("allowlist")
    require(type(upstream) is dict, "SciPy upstream missing")
    require(type(rows) is list and len(rows) == 2, "SciPy allowlist drift")
    objects = []
    for index, row in enumerate(rows):
        require(type(row) is dict, "SciPy object authority invalid")
        objects.append(
            code_evidence(
                download(str(row.get("raw_url"))),
                family=family,
                source_id=f"code.scipy.project.{index}",
                path=str(row.get("path")),
                size=row.get("raw_bytes"),
                blob=str(row.get("git_blob_sha1")),
            )
        )
    commit = upstream.get("commit_sha")
    blobs = scipy_license_blobs(config)
    licenses = []
    for path, blob in sorted(blobs.items()):
        phrases: tuple[str, ...] = ()
        if path == "LICENSE.txt":
            phrases = ("redistribution and use in source and binary forms",)
        raw = download(
            f"https://raw.githubusercontent.com/scipy/scipy/{commit}/{path}",
            200_000,
        )
        licenses.append(
            license_evidence(
                raw,
                family=family,
                path=path,
                blob=blob,
                phrases=phrases,
            )
        )
    return objects, {
        "family": family,
        "tree_sha": upstream.get("tree_sha"),
        "licenses": licenses,
    }


def execute(root: Path) -> dict[str, Any]:
    pydantic = pydantic_materialization(load_config(root, "pydantic"))
    pandas = single_materialization(load_config(root, "pandas"), "Pandas")
    typer = single_materialization(load_config(root, "typer"), "Typer")
    scipy = scipy_materialization(load_config(root, "scipy"))
    family_rows = [
        ("github:pydantic/pydantic", *pydantic),
        ("github:pandas-dev/pandas", *pandas),
        ("github:fastapi/typer", *typer),
        ("code.scipy.project", *scipy),
    ]
    objects = [
        row
        for _family, family_objects, _license in family_rows
        for row in family_objects
    ]
    total = sum(row["raw_bytes"] for row in objects)
    require(len(family_rows) == EXPECTED_FAMILIES, "family count drift")
    require(len(objects) == EXPECTED_OBJECTS, "object count drift")
    require(total == EXPECTED_BYTES, "candidate byte arithmetic drift")
    object_set = sorted(
        (
            row["family"],
            row["source_id"],
            row["path"],
            row["raw_bytes"],
            row["git_blob_sha1"],
            row["sha256"],
        )
        for row in objects
    )
    license_set = sorted(
        (family, sha256(canonical(license)))
        for family, _objects, license in family_rows
    )
    return {
        "schema_version": "12-6.d03-four-code-source-physical-materialization.v1",
        "status": "PHYSICAL_EXACT_SOURCE_BYTES_MATERIALIZED_ZERO_CREDIT",
        "source_family_count": len(family_rows),
        "object_count": len(objects),
        "candidate_raw_bytes": total,
        "object_set_sha256": sha256(canonical(object_set)),
        "license_set_sha256": sha256(canonical(license_set)),
        "objects": object_set,
        "licenses": license_set,
        "truth_boundary": {
            "canonical_capacity_credit_bytes": 0,
            "canonical_family_credit": 0,
            "global_cross_source_dedup_executed": False,
            "reserved_evaluation_decontamination_executed": False,
            "balance_diversity_retest_executed": False,
            "tokenizer_fit_authorized": False,
            "authorized_optimized_target_exposure": 0,
            "optimizer_updates_executed_on_real_targets": 0,
            "training_executed": False,
            "learned_weights_created": False,
            "final_test_outcomes_read": False,
            "paid_compute_used": False,
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(allow_abbrev=False)
    parser.add_argument("--repo-root", type=Path, default=Path("."))
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        summary = execute(args.repo_root.resolve())
        payload = canonical(summary)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        with args.output.open("xb") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
    except (OSError, ValueError, MaterializationError) as exc:
        print(
            json.dumps(
                {
                    "status": "BLOCKED_PHYSICAL_SOURCE_MATERIALIZATION",
                    "canonical_capacity_credit_bytes": 0,
                    "authorized_optimized_target_exposure": 0,
                    "error": str(exc),
                },
                sort_keys=True,
                separators=(",", ":"),
            )
        )
        return 2
    print(
        json.dumps(
            {
                "status": summary["status"],
                "candidate_raw_bytes": summary["candidate_raw_bytes"],
                "object_count": summary["object_count"],
                "source_family_count": summary["source_family_count"],
                "object_set_sha256": summary["object_set_sha256"],
                "license_set_sha256": summary["license_set_sha256"],
                "summary_sha256": sha256(payload),
                "canonical_capacity_credit_bytes": 0,
                "authorized_optimized_target_exposure": 0,
            },
            sort_keys=True,
            separators=(",", ":"),
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
