#!/usr/bin/env python3
"""Materialize a bounded CPython stdlib source candidate with zero training credit."""
from __future__ import annotations

import argparse
import ast
import hashlib
import io
import json
import re
import tarfile
import urllib.request
from pathlib import Path
from typing import Any

SCHEMA = "12-6.d03-cpython-stdlib-candidate.v1"
UPSTREAM_REPO = "python/cpython"
UPSTREAM_COMMIT = "23180c50082fe98784c78511b335d7274ed87fb7"
UPSTREAM_TREE = "8853f9fbbf23d2a8c8b7afc9ecab242a482125f2"
LICENSE_BLOB_SHA1 = "20cf39097c68baa17cc566b64e76d34ebf034044"
FAMILY_ID = "code.python.cpython"
MAX_SELECTED_BYTES = 1_200_000
MAX_ARCHIVE_BYTES = 80 * 1024 * 1024
DOWNLOAD_URL = f"https://codeload.github.com/python/cpython/tar.gz/{UPSTREAM_COMMIT}"
TREE_URL = f"https://api.github.com/repos/python/cpython/git/trees/{UPSTREAM_TREE}?recursive=1"

# Deliberately bounded to CPython-owned, pure-Python stdlib surfaces.  Anything not
# explicitly covered stays at zero credit.  Tests, vendored/third-party code,
# generated surfaces and installer bundles are excluded independently below.
ALLOWED_ROOTS = (
    "Lib/argparse.py",
    "Lib/ast.py",
    "Lib/base64.py",
    "Lib/bisect.py",
    "Lib/calendar.py",
    "Lib/cmd.py",
    "Lib/code.py",
    "Lib/codecs.py",
    "Lib/colorsys.py",
    "Lib/contextlib.py",
    "Lib/copy.py",
    "Lib/csv.py",
    "Lib/dataclasses.py",
    "Lib/datetime.py",
    "Lib/difflib.py",
    "Lib/dis.py",
    "Lib/doctest.py",
    "Lib/email/",
    "Lib/enum.py",
    "Lib/fnmatch.py",
    "Lib/fractions.py",
    "Lib/functools.py",
    "Lib/getopt.py",
    "Lib/getpass.py",
    "Lib/glob.py",
    "Lib/gzip.py",
    "Lib/hashlib.py",
    "Lib/heapq.py",
    "Lib/hmac.py",
    "Lib/http/",
    "Lib/inspect.py",
    "Lib/io.py",
    "Lib/ipaddress.py",
    "Lib/json/",
    "Lib/logging/",
    "Lib/lzma.py",
    "Lib/mailbox.py",
    "Lib/mimetypes.py",
    "Lib/netrc.py",
    "Lib/ntpath.py",
    "Lib/numbers.py",
    "Lib/operator.py",
    "Lib/os.py",
    "Lib/pathlib/",
    "Lib/pickle.py",
    "Lib/pkgutil.py",
    "Lib/platform.py",
    "Lib/posixpath.py",
    "Lib/pprint.py",
    "Lib/profile.py",
    "Lib/pstats.py",
    "Lib/queue.py",
    "Lib/random.py",
    "Lib/re/",
    "Lib/reprlib.py",
    "Lib/shlex.py",
    "Lib/shutil.py",
    "Lib/signal.py",
    "Lib/site.py",
    "Lib/socket.py",
    "Lib/sqlite3/",
    "Lib/statistics.py",
    "Lib/string.py",
    "Lib/subprocess.py",
    "Lib/tarfile.py",
    "Lib/textwrap.py",
    "Lib/threading.py",
    "Lib/timeit.py",
    "Lib/tokenize.py",
    "Lib/trace.py",
    "Lib/traceback.py",
    "Lib/types.py",
    "Lib/typing.py",
    "Lib/urllib/",
    "Lib/uuid.py",
    "Lib/warnings.py",
    "Lib/weakref.py",
    "Lib/zipfile/",
)
FORBIDDEN_PARTS = {
    "test",
    "tests",
    "idle_test",
    "_bundled",
    "vendor",
    "vendored",
    "third_party",
    "site-packages",
}
GENERATED_MARKERS = (
    "generated by",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "do not edit",
)
SECRET_PATTERNS = (
    re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(r"\bgh[pousr]_[A-Za-z0-9]{20,}\b"),
    re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    re.compile(r"\bsk-[A-Za-z0-9]{24,}\b"),
    re.compile(r"(?im)^\s*(?:api[_-]?key|secret|password)\s*=\s*['\"][^'\"]{12,}['\"]"),
)
NON_PSF_SPDX = re.compile(r"SPDX-License-Identifier:\s*([^\s*]+)", re.IGNORECASE)
ALLOWED_SPDX = {"PSF-2.0", "0BSD"}


class CandidateError(RuntimeError):
    """Fail-closed materialization error."""


def canonical_json_bytes(value: Any) -> bytes:
    return (
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        + "\n"
    ).encode("utf-8")


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def git_blob_sha1(value: bytes) -> str:
    header = f"blob {len(value)}\0".encode("ascii")
    return hashlib.sha1(header + value).hexdigest()  # noqa: S324 - Git object identity


def _strip_archive_prefix(name: str) -> str:
    normalized = name.replace("\\", "/")
    if normalized.startswith("/") or "\x00" in normalized:
        raise CandidateError("unsafe archive path")
    parts = [part for part in normalized.split("/") if part not in {"", "."}]
    if not parts or any(part == ".." for part in parts):
        raise CandidateError("unsafe archive path")
    expected_root = f"cpython-{UPSTREAM_COMMIT}"
    if parts[0] != expected_root:
        raise CandidateError("archive root does not match pinned CPython commit")
    if len(parts) == 1:
        return ""
    return "/".join(parts[1:])


def _allowed_path(path: str) -> bool:
    if not path.endswith(".py"):
        return False
    parts = path.split("/")
    if any(part.lower() in FORBIDDEN_PARTS for part in parts):
        return False
    return any(
        path == root or (root.endswith("/") and path.startswith(root))
        for root in ALLOWED_ROOTS
    )


def _validate_source(path: str, raw: bytes) -> str:
    if not raw or b"\x00" in raw:
        raise CandidateError(f"{path}: empty or binary-like payload")
    try:
        text = raw.decode("utf-8", errors="strict")
    except UnicodeDecodeError as exc:
        raise CandidateError(f"{path}: non-UTF8 source") from exc
    head = text[:12_000].lower()
    if any(marker in head for marker in GENERATED_MARKERS):
        raise CandidateError(f"{path}: generated-code marker")
    for match in NON_PSF_SPDX.finditer(text[:12_000]):
        if match.group(1) not in ALLOWED_SPDX:
            raise CandidateError(f"{path}: non-PSF SPDX license marker")
    if any(pattern.search(text) for pattern in SECRET_PATTERNS):
        raise CandidateError(f"{path}: secret-like content")
    try:
        tree = ast.parse(text, filename=path)
        compile(tree, path, "exec")
    except (SyntaxError, ValueError) as exc:
        raise CandidateError(f"{path}: Python parse/compile failure") from exc
    return text


def _read_members(archive_bytes: bytes) -> list[tuple[str, bytes]]:
    if len(archive_bytes) > MAX_ARCHIVE_BYTES:
        raise CandidateError("archive exceeds compressed-byte safety limit")
    rows: list[tuple[str, bytes]] = []
    try:
        archive = tarfile.open(fileobj=io.BytesIO(archive_bytes), mode="r:gz")
    except tarfile.TarError as exc:
        raise CandidateError("invalid gzip tar archive") from exc
    with archive:
        for member in archive.getmembers():
            path = _strip_archive_prefix(member.name)
            if member.issym() or member.islnk():
                if _allowed_path(path):
                    raise CandidateError(f"{path}: links forbidden")
                continue
            if not member.isfile() or not _allowed_path(path):
                continue
            if member.size < 1 or member.size > 1_000_000:
                raise CandidateError(f"{path}: invalid source size")
            stream = archive.extractfile(member)
            if stream is None:
                raise CandidateError(f"{path}: unreadable source member")
            raw = stream.read(member.size + 1)
            if len(raw) != member.size:
                raise CandidateError(f"{path}: source size mismatch")
            rows.append((path, raw))
    if not rows:
        raise CandidateError("no eligible stdlib Python sources found")
    rows.sort(key=lambda item: item[0])
    if len({path for path, _ in rows}) != len(rows):
        raise CandidateError("duplicate archive member path")
    return rows


def materialize_archive_bytes(
    archive_bytes: bytes,
    *,
    expected_blobs: dict[str, str],
    byte_cap: int = MAX_SELECTED_BYTES,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    if byte_cap < 1 or byte_cap > MAX_SELECTED_BYTES:
        raise CandidateError("byte_cap outside allowed range")
    if not expected_blobs:
        raise CandidateError("exact Git tree blob map is required")
    members = _read_members(archive_bytes)
    selected: list[dict[str, Any]] = []
    seen_payloads: dict[str, str] = {}
    retained = 0
    skipped_for_cap = 0
    for path, raw in members:
        expected_blob = expected_blobs.get(path)
        if expected_blob is None:
            raise CandidateError(f"{path}: absent from pinned Git tree")
        observed_blob = git_blob_sha1(raw)
        if observed_blob != expected_blob:
            raise CandidateError(f"{path}: Git blob does not match pinned tree")
        _validate_source(path, raw)
        digest = sha256_bytes(raw)
        if digest in seen_payloads:
            raise CandidateError(
                f"exact duplicate source payload: {seen_payloads[digest]} and {path}"
            )
        seen_payloads[digest] = path
        if retained + len(raw) > byte_cap:
            skipped_for_cap += 1
            continue
        retained += len(raw)
        selected.append(
            {
                "record_id": f"cpython:{path}",
                "source_path": path,
                "family": FAMILY_ID,
                "modality": "code",
                "git_blob_sha1": observed_blob,
                "payload_sha256": digest,
                "payload_bytes": len(raw),
                "text": raw.decode("utf-8"),
                "training_eligible": False,
                "evaluation_eligible": False,
            }
        )
    if not selected:
        raise CandidateError("byte cap retained no source objects")
    projection = [
        {key: value for key, value in row.items() if key != "text"}
        for row in selected
    ]
    inventory_identity = sha256_bytes(canonical_json_bytes(projection))
    report: dict[str, Any] = {
        "schema_version": SCHEMA,
        "execution_profile": "LOCAL_FREE",
        "source": {
            "repository": UPSTREAM_REPO,
            "commit": UPSTREAM_COMMIT,
            "tree": UPSTREAM_TREE,
            "license_blob_sha1": LICENSE_BLOB_SHA1,
            "family_id": FAMILY_ID,
        },
        "selection": {
            "policy": "EXPLICIT_CPYTHON_OWNED_PURE_PYTHON_STDLIB_ALLOWLIST_V1",
            "byte_cap": byte_cap,
            "eligible_archive_objects": len(members),
            "selected_objects": len(selected),
            "selected_bytes": retained,
            "skipped_for_cap": skipped_for_cap,
            "inventory_identity_sha256": inventory_identity,
            "pinned_tree_verified_for_every_selected_object": True,
        },
        "rights": {
            "license": "PSF-2.0",
            "root_psf_license_training_compatible": True,
            "selected_objects_rights_admitted": False,
            "file_level_incorporated_license_retest_required": True,
            "incorporated_software_blanket_admission": False,
            "only_allowlisted_objects_considered": True,
            "redistribution_requires_license_notice_and_change_summary": True,
        },
        "truth_boundary": {
            "status": "CANDIDATE_MATERIALIZED_ZERO_CREDIT",
            "canonical_corpus_admitted": False,
            "canonical_capacity_credit_bytes": 0,
            "family_count_credit_added": 0,
            "training_authorized_bytes": 0,
            "unique_causal_loss_positions": 0,
            "tokenizer_fit_executed": False,
            "optimizer_updates": 0,
            "model_training_executed": False,
            "final_test_accessed": False,
            "paid_compute_used": False,
        },
        "mandatory_successors": [
            "file_level_incorporated_license_retest",
            "global_cross_source_dedup",
            "fresh_reserved_evaluation_decontamination",
            "post_composition_quality_and_privacy",
            "balance_and_family_caps",
            "cluster_safe_split",
            "deterministic_packing_and_two_clean_builds",
            "positive_exact_unique_causal_loss_ledger",
        ],
    }
    report["report_identity_sha256"] = sha256_bytes(canonical_json_bytes(report))
    return selected, report


def fetch_pinned_tree_blobs(
    url: str = TREE_URL,
    *,
    timeout: float = 60.0,
) -> dict[str, str]:
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": "12-6-ai-cpython-stdlib/1.0 (+LOCAL_FREE research)",
            "Accept": "application/vnd.github+json",
        },
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        payload = json.load(response)
    if payload.get("sha") != UPSTREAM_TREE or payload.get("truncated") is not False:
        raise CandidateError("GitHub tree response is not complete pinned-tree authority")
    tree = payload.get("tree")
    if not isinstance(tree, list):
        raise CandidateError("invalid GitHub tree response")
    blobs: dict[str, str] = {}
    for entry in tree:
        if not isinstance(entry, dict) or entry.get("type") != "blob":
            continue
        path = entry.get("path")
        blob = entry.get("sha")
        if isinstance(path, str) and isinstance(blob, str):
            blobs[path] = blob
    if blobs.get("LICENSE") != LICENSE_BLOB_SHA1:
        raise CandidateError("pinned CPython LICENSE blob mismatch")
    if not any(_allowed_path(path) for path in blobs):
        raise CandidateError("pinned Git tree contains no eligible stdlib objects")
    return blobs


def download_archive(url: str = DOWNLOAD_URL, *, timeout: float = 60.0) -> bytes:
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": "12-6-ai-cpython-stdlib/1.0 (+LOCAL_FREE research)",
            "Accept": "application/gzip",
        },
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        length = response.headers.get("Content-Length")
        if length is not None and int(length) > MAX_ARCHIVE_BYTES:
            raise CandidateError("remote archive exceeds compressed-byte limit")
        data = response.read(MAX_ARCHIVE_BYTES + 1)
    if len(data) > MAX_ARCHIVE_BYTES:
        raise CandidateError("remote archive exceeds compressed-byte limit")
    return data


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--archive", type=Path)
    parser.add_argument("--records", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--byte-cap", type=int, default=MAX_SELECTED_BYTES)
    args = parser.parse_args()
    expected_blobs = fetch_pinned_tree_blobs()
    archive_bytes = args.archive.read_bytes() if args.archive else download_archive()
    rows, report = materialize_archive_bytes(
        archive_bytes,
        expected_blobs=expected_blobs,
        byte_cap=args.byte_cap,
    )
    args.records.parent.mkdir(parents=True, exist_ok=True)
    args.report.parent.mkdir(parents=True, exist_ok=True)
    with args.records.open("w", encoding="utf-8", newline="\n") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n")
    args.report.write_bytes(canonical_json_bytes(report))
    print(
        f"{report['truth_boundary']['status']} "
        f"objects={report['selection']['selected_objects']} "
        f"bytes={report['selection']['selected_bytes']} "
        f"report={report['report_identity_sha256']}"
    )


if __name__ == "__main__":
    main()
