#!/usr/bin/env python3
"""Exact, fail-closed Pydantic source qualification for NEXT100-048.

The verifier intentionally separates GitHub API metadata calls from immutable raw
object downloads. API calls use the Actions token when available so scientific
source admission is not coupled to the anonymous GitHub API rate limit.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
import math
import os
import re
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any

WORKER = "NEXT100-048-CODE-PYDANTIC"
HISTORICAL_SCHEMA = "12-6.next100-048-pydantic-source-admission.v1"
SCHEMA = "12-6.next100-048-pydantic-source-admission.v2"
HISTORICAL_AUTHORITY_IDENTITY_SHA256 = (
    "a25e618f4e26dd7c0df643768ab867a7ae080ca6ad2e5a88bda89bc757ae183a"
)
PYDANTIC_POLICY_BLOB = "504ef934145ed0711743f781dc9f47b07ad7accd"
DATA227_HEAD = "8ebdb2e132ed7bae5245e9d4c140752640ab9885"
DATA227_POLICY_BLOB = "0ce5223a1cade10031899bf27348a1a65121d4c6"
DATA227_POLICY_PATH = Path("configs/data/data227_code_rights_policy_v1.json")
EVAL289_HEAD = "1c870e5e02bf48891ca599b0b3f3bfe6e84425bc"
UPSTREAM_COMMIT = "cf67d4b3193c3fe43ede18612ed62785eee11382"
TAG_OBJECT = "07b73712023f052c7c008c4a9c5121b4894e44ec"
LICENSE_BLOB = "488c6260c10f2e88fa1fae58a63fccec8d600cd1"
LICENSE_SHA256 = "a9e186f3ca16b5eef84318e7a701721351a00cb7b8ae3a4394b67b49e3529ef3"
EXPECTED_OBJECTS = (
    (
        "code.pydantic.pydantic.main",
        "pydantic/main.py",
        "2ed62e5f3eded5d1e6b0052130e8d5f8627a60c6",
        85_334,
        "35b842cfe92ef300e060b40c062ef93afee1cb075cf0b7b0037a1434867c2554",
    ),
    (
        "code.pydantic.pydantic.fields",
        "pydantic/fields.py",
        "ede966fa8010c070fede69d8f048b618a1b38f17",
        82_023,
        "6bc66125f23c143e934030fbf9c58c9b5657950bdad3031d4f6132e55bd57be3",
    ),
    (
        "code.pydantic.pydantic.type_adapter",
        "pydantic/type_adapter.py",
        "d962305f2c923a6046b8234a334bdca0e644b159",
        36_123,
        "4f4e60f1641ccc1b1553fdf945d2b1823222ed8ecb222a7aee9177348ed7e061",
    ),
    (
        "code.pydantic.pydantic.functional_validators",
        "pydantic/functional_validators.py",
        "558e99c1e7a09e3c894d769c96cb28e25dc537ca",
        31_724,
        "ee9fb88ef3ffffd8d9caf71d5e289d7b9a406bf26533b7c9d41824a9b8f14963",
    ),
)
NEAR_THRESHOLD = 0.85
SHINGLE_SIZE = 5

SECRET_PATTERNS = (
    re.compile(rb"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(rb"\bgh[pousr]_[A-Za-z0-9_]{20,}\b"),
    re.compile(rb"\bsk-[A-Za-z0-9_-]{20,}\b"),
    re.compile(rb"\bAKIA[0-9A-Z]{16}\b"),
)
PRIVACY_CREDENTIAL_PATTERNS = (
    re.compile(rb"(?i)https?://[^/\s:@]+:[^/\s@]+@"),
    re.compile(
        rb"(?i)\b(?:password|passwd|api[_-]?key|secret)\s*=\s*['\"][A-Za-z0-9_+./=-]{24,}['\"]"
    ),
)
GENERATED_PATTERNS = (
    re.compile(r"(?i)\bcode generated\b.{0,120}\bdo not edit\b"),
    re.compile(r"(?i)<auto-generated(?:\s|>)"),
    re.compile(r"(?i)\bautomatically generated\b"),
    re.compile(r"(?i)\bthis file (?:is|was) generated\b"),
    re.compile(r"(?i)(?:^|\s)@generated(?:\s|$)"),
)


class QualificationError(RuntimeError):
    """Fail-closed source qualification error."""


def require(condition: bool, message: str) -> None:
    if not condition:
        raise QualificationError(message)


def _strict_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    value: dict[str, Any] = {}
    for key, item in pairs:
        if key in value:
            raise QualificationError(f"duplicate JSON key: {key}")
        value[key] = item
    return value


def _reject_constant(value: str) -> None:
    raise QualificationError(f"non-finite JSON number: {value}")


def _strict_float(value: str) -> float:
    parsed = float(value)
    if not math.isfinite(parsed):
        raise QualificationError(f"non-finite JSON number: {value}")
    return parsed


def _load_json_bytes(raw: bytes, *, context: str) -> dict[str, Any]:
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise QualificationError(f"invalid UTF-8 JSON for {context}: {exc}") from exc
    try:
        value = json.loads(
            text,
            object_pairs_hook=_strict_object,
            parse_constant=_reject_constant,
            parse_float=_strict_float,
        )
    except json.JSONDecodeError as exc:
        raise QualificationError(f"invalid JSON for {context}: {exc}") from exc
    require(type(value) is dict, f"JSON root is not an object: {context}")
    return value


def git_blob_sha1(data: bytes) -> str:
    return hashlib.sha1(f"blob {len(data)}\0".encode("ascii") + data).hexdigest()  # noqa: S324


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _headers(url: str) -> dict[str, str]:
    headers = {"User-Agent": "12-6-NEXT100-048-Pydantic/2"}
    host = urllib.parse.urlparse(url).hostname
    token = os.environ.get("GITHUB_TOKEN")
    if token and host == "api.github.com":
        headers["Authorization"] = f"Bearer {token}"
        headers["Accept"] = "application/vnd.github+json"
        headers["X-GitHub-Api-Version"] = "2022-11-28"
    return headers


def download(url: str, max_bytes: int = 300_000) -> bytes:
    request = urllib.request.Request(url, headers=_headers(url))
    try:
        with urllib.request.urlopen(request, timeout=45) as response:
            data = response.read(max_bytes + 1)
    except Exception as exc:  # urllib exposes several transport exception classes
        raise QualificationError(f"download failed for {url}: {exc}") from exc
    require(len(data) <= max_bytes, f"bounded download exceeded {max_bytes}: {url}")
    return data


def load_json(url: str, max_bytes: int = 200_000) -> dict[str, Any]:
    return _load_json_bytes(download(url, max_bytes), context=url)


def load_data227_policy(repo_root: Path) -> dict[str, Any]:
    """Load the exact predecessor policy without making current-main depend on its file."""
    local_path = repo_root / DATA227_POLICY_PATH
    if local_path.is_file():
        raw = local_path.read_bytes()
    else:
        raw = download(
            "https://raw.githubusercontent.com/Oleksii-debug/12-6-ai./"
            + DATA227_HEAD
            + "/"
            + DATA227_POLICY_PATH.as_posix(),
            max_bytes=100_000,
        )
    require(git_blob_sha1(raw) == DATA227_POLICY_BLOB, "DATA-227 policy blob drift")
    return _load_json_bytes(raw, context="DATA-227 policy")


def token_shingles(text: str) -> set[tuple[str, ...]]:
    tokens = re.findall(r"[A-Za-z_][A-Za-z0-9_]*|\d+|[^\s]", text.casefold())
    if len(tokens) < SHINGLE_SIZE:
        return set()
    return {
        tuple(tokens[i : i + SHINGLE_SIZE])
        for i in range(len(tokens) - SHINGLE_SIZE + 1)
    }


def near_jaccard(left: str, right: str) -> float:
    a, b = token_shingles(left), token_shingles(right)
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def qualify(*, repo_root: Path, policy_path: Path, source_sha: str) -> dict[str, Any]:
    policy_raw = (repo_root / policy_path).read_bytes()
    require(
        git_blob_sha1(policy_raw) == PYDANTIC_POLICY_BLOB,
        "Pydantic rights policy blob drift",
    )
    policy = _load_json_bytes(policy_raw, context=str(policy_path))
    require(policy["schema_version"] == "12-6.next100-048-pydantic-code-rights.v1", "policy schema drift")
    require(policy["policy_ref"] == "policy://12-6/data/explicit-model-training-evidence-v1", "policy purpose drift")
    require(policy["source_family"] == "github:pydantic/pydantic", "source family drift")
    require(policy["upstream_commit"] == UPSTREAM_COMMIT, "upstream commit drift")
    require(policy["upstream_tag_object"] == TAG_OBJECT, "tag object drift")
    require(policy["license"]["blob_sha1"] == LICENSE_BLOB, "license blob drift")
    decisions = policy["decisions"]
    require(len(decisions) == 4, "expected four bounded Pydantic objects")
    require(sum(int(row["size_bytes"]) for row in decisions) == 235_204, "capacity drift")
    require(all(row["capacity_counted"] is True for row in decisions), "non-counted object entered bounded set")
    require(all(row["authorship_class"] == "UPSTREAM_AUTHORED_IMPLEMENTATION" for row in decisions), "authorship drift")

    repo_meta = load_json("https://api.github.com/repos/pydantic/pydantic")
    require(repo_meta["html_url"] == "https://github.com/pydantic/pydantic", "upstream repository identity drift")
    require(repo_meta["fork"] is False and repo_meta["mirror_url"] is None, "upstream is fork/mirror")

    tag_ref = load_json("https://api.github.com/repos/pydantic/pydantic/git/ref/tags/v2.13.4")
    require(tag_ref["object"]["sha"] == TAG_OBJECT, "tag ref drift")
    require(tag_ref["object"]["type"] == "tag", "expected annotated tag")
    tag = load_json(f"https://api.github.com/repos/pydantic/pydantic/git/tags/{TAG_OBJECT}")
    require(tag["object"]["sha"] == UPSTREAM_COMMIT, "tag commit drift")
    require(tag["object"]["type"] == "commit", "tag target is not commit")

    license_bytes = download(policy["license"]["url"])
    require(git_blob_sha1(license_bytes) == LICENSE_BLOB, "license Git blob drift")
    license_text = license_bytes.decode("utf-8", errors="strict")
    license_semantic_text = " ".join(license_text.split())
    for phrase in (
        "The MIT License (MIT)",
        "deal in the Software without restriction",
        "use, copy, modify, merge, publish, distribute, sublicense, and/or sell",
        "copyright notice and this permission notice shall be included",
    ):
        require(phrase in license_semantic_text, f"MIT grant phrase missing: {phrase}")

    objects: list[dict[str, Any]] = []
    texts: dict[str, str] = {}
    for decision in decisions:
        raw = download(decision["raw_url"])
        require(len(raw) == decision["size_bytes"], f"{decision['source_id']}: size drift")
        require(git_blob_sha1(raw) == decision["blob_sha1"], f"{decision['source_id']}: Git blob drift")
        require(b"\x00" not in raw, f"{decision['source_id']}: NUL byte")
        text = raw.decode("utf-8", errors="strict")
        require("\ufffd" not in text, f"{decision['source_id']}: replacement character")
        require(not any(0xD800 <= ord(ch) <= 0xDFFF for ch in text), f"{decision['source_id']}: surrogate code point")
        header = text[:8192]
        require(not any(pattern.search(header) for pattern in GENERATED_PATTERNS), f"{decision['source_id']}: generated-material marker")
        require(not any(pattern.search(raw) for pattern in SECRET_PATTERNS), f"{decision['source_id']}: secret pattern")
        require(not any(pattern.search(raw) for pattern in PRIVACY_CREDENTIAL_PATTERNS), f"{decision['source_id']}: credential literal")
        ast.parse(text, filename=decision["path"])
        digest = sha256(raw)
        objects.append(
            {
                "source_id": decision["source_id"],
                "source_family": decision["source_family"],
                "commit": decision["commit"],
                "path": decision["path"],
                "git_blob_sha1": decision["blob_sha1"],
                "size_bytes": len(raw),
                "raw_sha256": digest,
                "normalized_sha256": digest,
                "normalization_policy": "STRICT_UTF8_IDENTITY_PRESERVE_V1",
                "parse_validity": "PASS_AST_PARSE_PY311",
                "secret_scan": "PASS_DATA227_SECRET_PATTERNS",
                "privacy_credential_scan": "PASS_NO_CREDENTIAL_BEARING_LITERAL_PATTERN",
                "generated_material": False,
                "authorship_class": decision["authorship_class"],
                "capacity_counted": True,
                "training_purpose_decision": "ALLOWED",
                "redistribution_decision": "ALLOWED_WITH_MIT_NOTICE",
            }
        )
        texts[decision["source_id"]] = text

    raw_hashes = [row["raw_sha256"] for row in objects]
    exact_duplicates = sorted({value for value in raw_hashes if raw_hashes.count(value) > 1})
    require(not exact_duplicates, "exact duplicate selected objects")

    prior_policy = load_data227_policy(repo_root)
    prior_families = sorted({row["source_family"] for row in prior_policy["decisions"]})
    require(prior_families == ["github:encode/httpx", "github:psf/requests"], "DATA-227 family drift")
    comparison_texts = dict(texts)
    for prior in prior_policy["decisions"]:
        raw = download(prior["raw_url"])
        require(len(raw) == prior["size_bytes"], f"{prior['source_id']}: DATA-227 size drift")
        require(git_blob_sha1(raw) == prior["blob_sha1"], f"{prior['source_id']}: DATA-227 blob drift")
        comparison_texts[prior["source_id"]] = raw.decode("utf-8", errors="strict")

    near_pairs: list[dict[str, Any]] = []
    max_pair: list[str] | None = None
    max_score = -1.0
    ids = sorted(comparison_texts)
    for index, left in enumerate(ids):
        for right in ids[index + 1 :]:
            score = near_jaccard(comparison_texts[left], comparison_texts[right])
            if score > max_score:
                max_score = score
                max_pair = [left, right]
            if score >= NEAR_THRESHOLD:
                near_pairs.append({"left": left, "right": right, "jaccard": score})
    require(not near_pairs, "near-duplicate threshold violated")

    eval289 = load_json(
        "https://raw.githubusercontent.com/Oleksii-debug/12-6-ai./"
        + EVAL289_HEAD
        + "/evidence/eval289/code-evaluation-rights-reservation.json"
    )
    require(eval289["reservation"]["active"] is False, "code evaluation reservation became active")
    require(eval289["reservation"]["objects"] == [], "reserved code object overlaps candidate")

    core: dict[str, Any] = {
        "schema_version": SCHEMA,
        "worker_id": WORKER,
        "status": "ADMIT",
        "authority": "EXTERNAL_REAL_CODE_SOURCE_TERMINAL_LOCAL_FREE",
        "worker_source_sha": source_sha,
        "candidate_policy_authority": {
            "schema_version": "12-6.next100-048-pydantic-code-rights.v1",
            "git_blob_sha1": PYDANTIC_POLICY_BLOB,
        },
        "predecessor_code_authority": {
            "data227_head_sha": DATA227_HEAD,
            "rights_policy_git_blob_sha1": DATA227_POLICY_BLOB,
            "near_duplicate_policy": {
                "reject_at_or_above_jaccard": NEAR_THRESHOLD,
                "shingle_tokens": SHINGLE_SIZE,
            },
            "source_family_count": 2,
            "source_families": prior_families,
        },
        "upstream": {
            "repository": "https://github.com/pydantic/pydantic",
            "tag": "v2.13.4",
            "tag_object_sha1": TAG_OBJECT,
            "commit": UPSTREAM_COMMIT,
            "tag_signature_status": "UNSIGNED",
            "repository_fork": False,
            "repository_mirror": False,
        },
        "license": {
            "license_id": "MIT",
            "path": "LICENSE",
            "git_blob_sha1": LICENSE_BLOB,
            "sha256": sha256(license_bytes),
            "model_training": "ALLOWED_BY_REVIEWED_MIT_GRANT",
            "derivatives": "ALLOWED",
            "redistribution": "ALLOWED_WITH_NOTICE",
            "notice_required": True,
        },
        "objects": objects,
        "checks": {
            "strict_utf8_identity_normalization": "PASS",
            "parse_validity": "PASS_4_OF_4",
            "secret_privacy": "PASS_4_OF_4",
            "generated_selected_count": 0,
            "generated_selected_bytes": 0,
            "exact_duplicate_sha256": exact_duplicates,
            "near_duplicate_threshold": NEAR_THRESHOLD,
            "near_duplicate_pairs": near_pairs,
            "max_observed_pair": max_pair,
            "max_observed_jaccard": max_score,
            "current_eval_reservation_active_at_eval289_head": False,
        },
        "source_family_accounting": {
            "new_source_family": "github:pydantic/pydantic",
            "independent_new_family_count": 1,
            "predecessor_family_count": 2,
            "resulting_family_count_if_registered": 3,
            "selected_implementation_object_count": 4,
            "selected_authored_capacity_bytes": 235_204,
            "generated_capacity_bytes": 0,
            "generated_capacity_objects": 0,
        },
        "excluded_capacity": policy["excluded_capacity"],
        "evaluation_boundary": {
            "eval289_head_sha": EVAL289_HEAD,
            "active_reserved_objects": 0,
            "selected_objects_overlap_active_reservation": False,
        },
        "execution": {
            "class": "LOCAL_FREE",
            "paid_compute_used": False,
            "model_training_executed": False,
            "network_use": "bounded immutable-source qualification only",
            "github_api_authenticated": bool(os.environ.get("GITHUB_TOKEN")),
        },
        "terminal_decision": (
            "ADMIT exact four-object Pydantic v2.13.4 implementation snapshot for training-source registration; "
            "do not count generated, legacy v1, docs/tests/examples, stubs, or pydantic-core as this family capacity."
        ),
    }
    canonical = (
        json.dumps(core, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n"
    ).encode("utf-8")
    return {**core, "authority_identity_sha256": sha256(canonical)}


def _verify_self_hash(value: dict[str, Any]) -> None:
    supplied = value.get("authority_identity_sha256")
    unsigned = dict(value)
    unsigned.pop("authority_identity_sha256", None)
    canonical = (
        json.dumps(unsigned, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n"
    ).encode("utf-8")
    require(supplied == sha256(canonical), "authority self-hash mismatch")


def verify_historical_evidence(value: dict[str, Any]) -> None:
    """Verify the immutable v1 evidence without relabeling it as regenerated v2."""
    _verify_self_hash(value)
    require(
        value.get("authority_identity_sha256") == HISTORICAL_AUTHORITY_IDENTITY_SHA256,
        "historical authority identity drift",
    )
    require(value.get("schema_version") == HISTORICAL_SCHEMA, "historical schema drift")
    require(value.get("status") == "ADMIT", "historical terminal status is not ADMIT")
    predecessor = value.get("predecessor_code_authority")
    require(type(predecessor) is dict, "historical predecessor authority missing")
    require(
        predecessor.get("rights_policy_git_blob_sha1") == DATA227_POLICY_BLOB,
        "historical DATA-227 policy blob drift",
    )
    accounting = value.get("source_family_accounting")
    require(type(accounting) is dict, "historical source-family accounting missing")
    require(
        type(accounting.get("selected_implementation_object_count")) is int
        and accounting["selected_implementation_object_count"] == 4,
        "historical object-count drift",
    )
    require(
        type(accounting.get("selected_authored_capacity_bytes")) is int
        and accounting["selected_authored_capacity_bytes"] == 235_204,
        "historical capacity drift",
    )
    execution = value.get("execution")
    require(type(execution) is dict, "historical execution boundary missing")
    require(execution.get("class") == "LOCAL_FREE", "historical execution class drift")
    require(execution.get("paid_compute_used") is False, "historical paid compute used")
    require(
        execution.get("model_training_executed") is False,
        "historical model training executed",
    )


def verify_evidence(
    value: dict[str, Any],
    *,
    expected_source_sha: str,
) -> None:
    """Verify newly generated v2 evidence against the externally expected source SHA."""
    require(
        len(expected_source_sha) == 40
        and all(ch in "0123456789abcdef" for ch in expected_source_sha),
        "expected source SHA must be lowercase 40-hex",
    )
    _verify_self_hash(value)
    require(value.get("schema_version") == SCHEMA, "generated evidence schema drift")
    require(
        value.get("worker_source_sha") == expected_source_sha,
        "generated worker source SHA drift",
    )
    candidate_policy = value.get("candidate_policy_authority")
    require(type(candidate_policy) is dict, "candidate policy authority missing")
    require(
        candidate_policy
        == {
            "schema_version": "12-6.next100-048-pydantic-code-rights.v1",
            "git_blob_sha1": PYDANTIC_POLICY_BLOB,
        },
        "candidate policy authority drift",
    )
    predecessor = value.get("predecessor_code_authority")
    require(type(predecessor) is dict, "generated predecessor authority missing")
    require(
        predecessor.get("data227_head_sha") == DATA227_HEAD,
        "generated DATA-227 head drift",
    )
    require(
        predecessor.get("rights_policy_git_blob_sha1") == DATA227_POLICY_BLOB,
        "generated DATA-227 policy blob drift",
    )
    require(
        predecessor.get("source_family_count") == 2
        and type(predecessor.get("source_family_count")) is int,
        "generated predecessor family count drift",
    )
    require(
        predecessor.get("source_families")
        == ["github:encode/httpx", "github:psf/requests"],
        "generated predecessor family drift",
    )
    require(
        predecessor.get("near_duplicate_policy")
        == {
            "reject_at_or_above_jaccard": NEAR_THRESHOLD,
            "shingle_tokens": SHINGLE_SIZE,
        },
        "generated predecessor near-dedup policy drift",
    )
    upstream = value.get("upstream")
    require(type(upstream) is dict, "generated upstream authority missing")
    require(
        upstream.get("repository") == "https://github.com/pydantic/pydantic"
        and upstream.get("commit") == UPSTREAM_COMMIT
        and upstream.get("tag_object_sha1") == TAG_OBJECT,
        "generated upstream identity drift",
    )
    license_authority = value.get("license")
    require(type(license_authority) is dict, "generated license authority missing")
    require(
        license_authority.get("license_id") == "MIT"
        and license_authority.get("git_blob_sha1") == LICENSE_BLOB
        and license_authority.get("sha256") == LICENSE_SHA256,
        "generated license authority drift",
    )
    objects = value.get("objects")
    require(
        type(objects) is list and len(objects) == len(EXPECTED_OBJECTS),
        "generated object cardinality drift",
    )
    expected_rows = {
        source_id: (path, blob, size, digest)
        for source_id, path, blob, size, digest in EXPECTED_OBJECTS
    }
    seen_ids: set[str] = set()
    for row in objects:
        require(type(row) is dict, "generated object row must be an object")
        source_id = row.get("source_id")
        require(type(source_id) is str and source_id in expected_rows, "generated source id drift")
        require(source_id not in seen_ids, "generated duplicate source id")
        seen_ids.add(source_id)
        path, blob, size, digest = expected_rows[source_id]
        require(
            row.get("source_family") == "github:pydantic/pydantic"
            and row.get("commit") == UPSTREAM_COMMIT
            and row.get("path") == path
            and row.get("git_blob_sha1") == blob
            and type(row.get("size_bytes")) is int
            and row.get("size_bytes") == size
            and row.get("raw_sha256") == digest
            and row.get("normalized_sha256") == digest
            and row.get("normalization_policy") == "STRICT_UTF8_IDENTITY_PRESERVE_V1"
            and row.get("capacity_counted") is True
            and row.get("generated_material") is False
            and row.get("authorship_class") == "UPSTREAM_AUTHORED_IMPLEMENTATION"
            and row.get("training_purpose_decision") == "ALLOWED"
            and row.get("redistribution_decision") == "ALLOWED_WITH_MIT_NOTICE",
            f"generated object authority drift: {source_id}",
        )
    require(seen_ids == set(expected_rows), "generated object set drift")
    evaluation = value.get("evaluation_boundary")
    require(type(evaluation) is dict, "generated evaluation boundary missing")
    require(
        evaluation.get("eval289_head_sha") == EVAL289_HEAD
        and evaluation.get("active_reserved_objects") == 0
        and type(evaluation.get("active_reserved_objects")) is int
        and evaluation.get("selected_objects_overlap_active_reservation") is False,
        "generated evaluation boundary drift",
    )
    require(value.get("status") == "ADMIT", "terminal status is not ADMIT")
    accounting = value.get("source_family_accounting")
    require(type(accounting) is dict, "source-family accounting missing")
    require(
        type(accounting.get("selected_implementation_object_count")) is int
        and accounting["selected_implementation_object_count"] == 4,
        "object-count drift",
    )
    require(
        type(accounting.get("selected_authored_capacity_bytes")) is int
        and accounting["selected_authored_capacity_bytes"] == 235_204,
        "capacity drift",
    )
    require(
        accounting.get("new_source_family") == "github:pydantic/pydantic"
        and type(accounting.get("independent_new_family_count")) is int
        and accounting.get("independent_new_family_count") == 1
        and type(accounting.get("predecessor_family_count")) is int
        and accounting.get("predecessor_family_count") == 2
        and type(accounting.get("resulting_family_count_if_registered")) is int
        and accounting.get("resulting_family_count_if_registered") == 3
        and type(accounting.get("generated_capacity_bytes")) is int
        and accounting.get("generated_capacity_bytes") == 0
        and type(accounting.get("generated_capacity_objects")) is int
        and accounting.get("generated_capacity_objects") == 0,
        "generated source-family accounting drift",
    )
    execution = value.get("execution")
    require(type(execution) is dict, "execution boundary missing")
    require(execution.get("class") == "LOCAL_FREE", "execution class drift")
    require(execution.get("paid_compute_used") is False, "paid compute used")
    require(execution.get("model_training_executed") is False, "model training executed")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path("."))
    parser.add_argument(
        "--policy",
        type=Path,
        default=Path("configs/data/next100_048_pydantic_code_rights_v1.json"),
    )
    parser.add_argument("--source-sha", default=os.environ.get("EXPECTED_SOURCE_SHA", ""))
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    require(len(args.source_sha) == 40, "exact worker source SHA is required")
    evidence = qualify(
        repo_root=args.repo_root.resolve(),
        policy_path=args.policy,
        source_sha=args.source_sha,
    )
    verify_evidence(evidence, expected_source_sha=args.source_sha)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(evidence, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n",
        encoding="utf-8",
    )
    print(
        json.dumps(
            {
                "status": evidence["status"],
                "capacity_bytes": evidence["source_family_accounting"]["selected_authored_capacity_bytes"],
                "authority_identity_sha256": evidence["authority_identity_sha256"],
                "github_api_authenticated": evidence["execution"]["github_api_authenticated"],
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
