#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ast
import hashlib
import json
import re
import subprocess
import urllib.request
from pathlib import Path

CONFIG = Path("configs/data/next100_050_pandas_code_source_v1.json")
NEAR_THRESHOLD = 0.85
SHINGLE_N = 5
SECRET_PATTERNS = (
    re.compile(rb"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(rb"\bgh[pousr]_[A-Za-z0-9_]{20,}\b"),
    re.compile(rb"\bsk-[A-Za-z0-9_-]{20,}\b"),
    re.compile(rb"\bAKIA[0-9A-Z]{16}\b"),
)
BANNED_PARTS = {"vendor", "vendored", "third_party", "third-party", "generated", "build", "dist", "node_modules"}
BANNED_SUFFIXES = (".pyx", ".pxd", ".pxi", ".so", ".dll", ".pyc", ".min.js", ".map")
GENERATED_MARKERS = (b"generated file", b"auto-generated", b"autogenerated", b"do not edit")


def cjson(value: object) -> bytes:
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n").encode()


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def git_blob_sha1(data: bytes) -> str:
    return hashlib.sha1(f"blob {len(data)}\0".encode() + data).hexdigest()


def download(url: str, max_bytes: int = 300_000) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "12-6-NEXT100-050-pandas-admission/1"})
    with urllib.request.urlopen(req, timeout=30) as response:
        data = response.read(max_bytes + 1)
    if len(data) > max_bytes:
        raise RuntimeError(f"bounded download exceeded {max_bytes}: {url}")
    return data


def shingles(text: str) -> set[tuple[str, ...]]:
    tokens = re.findall(r"[A-Za-z_][A-Za-z0-9_]*|\d+|[^\s]", text.casefold())
    return {tuple(tokens[i:i + SHINGLE_N]) for i in range(max(0, len(tokens) - SHINGLE_N + 1))}


def jaccard(a: str, b: str) -> float:
    sa, sb = shingles(a), shingles(b)
    if not sa or not sb:
        return 0.0
    return len(sa & sb) / len(sa | sb)


def raw_url(repo_url: str, commit: str, path: str) -> str:
    prefix = "https://github.com/"
    if not repo_url.startswith(prefix):
        raise RuntimeError(f"non-GitHub canonical repository: {repo_url}")
    slug = repo_url[len(prefix):].strip("/")
    return f"https://raw.githubusercontent.com/{slug}/{commit}/{path}"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--output", required=True)
    parser.add_argument("--source-sha", required=True)
    args = parser.parse_args()

    repo = Path(args.repo_root).resolve()
    actual_head = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo, text=True).strip()
    if actual_head != args.source_sha:
        raise RuntimeError(f"exact-head mismatch: {actual_head} != {args.source_sha}")

    cfg_bytes = (repo / CONFIG).read_bytes()
    cfg = json.loads(cfg_bytes)
    registry_path = repo / cfg["dedup_baseline"]["registry_path"]
    registry_bytes = registry_path.read_bytes()
    registry = json.loads(registry_bytes)

    upstream = cfg["upstream"]
    obj = cfg["object"]
    lic = cfg["license"]

    meta = json.loads(download(f"https://api.github.com/repos/{upstream['repository']}", 150_000))
    if meta.get("html_url") != upstream["repository_url"] or meta.get("fork") is not False or meta.get("mirror_url") is not None:
        raise RuntimeError("canonical upstream repository identity failed")
    if meta.get("archived") is True:
        raise RuntimeError("archived upstream repository excluded")

    path_parts = {p.casefold() for p in Path(obj["path"]).parts}
    if path_parts & BANNED_PARTS or obj["path"].casefold().endswith(BANNED_SUFFIXES):
        raise RuntimeError("generated/vendored/Cython/binary path excluded")
    if not obj["path"].endswith(".py"):
        raise RuntimeError("this bounded authority admits hand-authored Python only")

    raw = download(obj["raw_url"])
    if len(raw) != obj["size_bytes"]:
        raise RuntimeError("source size drift")
    if git_blob_sha1(raw) != obj["git_blob_sha1"]:
        raise RuntimeError("source Git blob identity drift")
    lowered_prefix = raw[:2048].lower()
    if any(marker in lowered_prefix for marker in GENERATED_MARKERS):
        raise RuntimeError("generated-code marker detected")
    for pattern in SECRET_PATTERNS:
        if pattern.search(raw):
            raise RuntimeError("secret-like material detected")
    text = raw.decode("utf-8", errors="strict")
    if text.encode("utf-8") != raw:
        raise RuntimeError("identity normalization failed")
    ast.parse(text, filename=obj["path"])
    compile(text, obj["path"], "exec", dont_inherit=True)

    license_bytes = download(lic["url"])
    if git_blob_sha1(license_bytes) != lic["git_blob_sha1"]:
        raise RuntimeError("license Git blob identity drift")
    license_text = license_bytes.decode("utf-8", errors="strict")
    required_license_phrases = (
        "BSD 3-Clause License",
        "Redistribution and use in source and binary forms, with or without",
        "modification, are permitted provided that the following conditions are met:",
        "Neither the name of the copyright holder nor the names of its",
    )
    if not all(phrase in license_text for phrase in required_license_phrases):
        raise RuntimeError("license grant/conditions drift")
    uses = cfg["rights_decision"]["uses"]
    if any(uses[k] != "ALLOWED" for k in ("acquisition", "storage", "analysis", "model_training", "redistribution")):
        raise RuntimeError("required training use is not explicitly approved")
    if uses.get("evaluation") != "NOT_SEPARATELY_ADMITTED":
        raise RuntimeError("training authority must not imply evaluation authority")

    raw_hash = sha256(raw)
    existing_code = [s for s in registry["sources"] if s.get("modality") == "code"]
    existing_families = sorted({s["independent_family_id"] for s in existing_code})
    if obj["source_family"] in existing_families:
        raise RuntimeError("pandas family already present in baseline registry")
    if raw_hash in {s["raw_sha256"] for s in existing_code} or raw_hash in {s["normalized_sha256"] for s in existing_code}:
        raise RuntimeError("exact duplicate of live code registry")

    comparisons = []
    for source in existing_code:
        prior = download(raw_url(source["canonical_repository"], source["commit"], source["path"]))
        if sha256(prior) != source["raw_sha256"]:
            raise RuntimeError(f"baseline registry source drift: {source['source_id']}")
        score = jaccard(text, prior.decode("utf-8", errors="strict"))
        comparisons.append({"against": source["source_id"], "family": source["independent_family_id"], "jaccard_5token": score})
        if score >= NEAR_THRESHOLD:
            raise RuntimeError(f"near duplicate >= {NEAR_THRESHOLD}: {source['source_id']}")

    source_manifest_core = {
        "source_id": obj["source_id"],
        "source_family": obj["source_family"],
        "source_version": f"git:{upstream['commit']}",
        "path": obj["path"],
        "raw_sha256": raw_hash,
        "normalized_sha256": raw_hash,
        "license_sha256": sha256(license_bytes),
        "policy_ref": cfg["policy_ref"],
    }
    source_manifest_sha256 = sha256(cjson(source_manifest_core))

    before_bytes = sum(int(s["raw_bytes"]) for s in existing_code)
    core = {
        "schema_version": "12-6.next100-050-pandas-terminal-source-authority.v1",
        "worker_id": cfg["worker_id"],
        "authority": "EXTERNAL_REAL_CODE_SOURCE_ADMISSION_LOCAL_FREE",
        "verdict": "ADMIT",
        "terminal": True,
        "source_sha": args.source_sha,
        "local_free_only": True,
        "upstream": {
            "repository": upstream["repository"],
            "repository_url": upstream["repository_url"],
            "fork": meta.get("fork"),
            "mirror_url": meta.get("mirror_url"),
            "archived": meta.get("archived"),
            "commit": upstream["commit"],
        },
        "object": {
            "source_id": obj["source_id"],
            "source_family": obj["source_family"],
            "family_identity_sha256": sha256(obj["source_family"].encode()),
            "path": obj["path"],
            "language": "python",
            "size_bytes": len(raw),
            "git_blob_sha1": git_blob_sha1(raw),
            "raw_sha256": raw_hash,
            "normalized_sha256": raw_hash,
            "normalization_policy": obj["normalization_policy"],
            "source_manifest_sha256": source_manifest_sha256,
            "syntax": {"ast_parse": "PASS", "compile": "PASS"},
            "generated_or_vendored": False,
            "cython_or_generated_c_artifact": False,
        },
        "license": {
            "license_id": lic["license_id"],
            "path": lic["path"],
            "git_blob_sha1": git_blob_sha1(license_bytes),
            "sha256": sha256(license_bytes),
            "grant_text_verified": True,
        },
        "rights": {
            "status": cfg["rights_decision"]["status"],
            "policy_ref": cfg["policy_ref"],
            "uses": uses,
            "basis": cfg["rights_decision"]["basis"],
            "redistribution_conditions": cfg["rights_decision"]["redistribution_conditions"],
        },
        "privacy_and_secrets": {
            "secret_patterns": "PASS",
            "privacy_classification": "PUBLIC_OPEN_SOURCE_IMPLEMENTATION_NO_USER_DATA_FIXTURES_SELECTED",
            "selected_tests_or_private_endpoints": False,
        },
        "deduplication": {
            "baseline_registry_path": cfg["dedup_baseline"]["registry_path"],
            "baseline_registry_git_blob_sha1": git_blob_sha1(registry_bytes),
            "baseline_registry_sha256": sha256(registry_bytes),
            "exact_duplicate": False,
            "near_threshold": NEAR_THRESHOLD,
            "comparisons": comparisons,
            "near_duplicate": False,
        },
        "family_accounting": {
            "existing_code_families": existing_families,
            "existing_family_count": len(existing_families),
            "admitted_family": obj["source_family"],
            "family_delta": 1,
            "resulting_family_count": len(existing_families) + 1,
            "existing_raw_code_bytes": before_bytes,
            "admitted_raw_code_bytes": len(raw),
            "resulting_raw_code_bytes": before_bytes + len(raw),
            "files_admitted": 1,
            "capacity_rule": "one upstream lineage family regardless of file count; generated/vendored/Cython-derived outputs add zero capacity",
        },
        "scope_exclusions": cfg["scope_exclusions"],
        "evaluation_boundary": cfg["evaluation_boundary"],
        "config_git_blob_sha1": git_blob_sha1(cfg_bytes),
        "config_sha256": sha256(cfg_bytes),
    }
    report = {**core, "report_sha256": sha256(cjson(core))}
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(cjson(report))
    print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
