#!/usr/bin/env python3
"""Deterministically qualify the NEXT100-049 bounded NumPy code source."""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
from pathlib import Path
import re
import sys
import urllib.error
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "configs/data/next100_049_numpy_code_source_authority_v1.json"
REGISTRY_PATH = ROOT / "data/registry/external_snapshots.v2.json"
USER_AGENT = "12-6-next100-049-numpy-source-qualifier/1.0"
GENERATED_MARKERS = (
    "this file is generated",
    "this file was generated",
    "auto-generated file",
    "autogenerated file",
    "do not edit this file",
    "generated by cython",
)
FORBIDDEN_PATH_PARTS = (
    "/tests/",
    "/benchmarks/",
    "/docs/",
    "/doc/",
    "/examples/",
    "/vendor/",
    "/vendored/",
    "/third_party/",
    "/code_generators/",
)
SECRET_PATTERNS = {
    "aws_access_key": re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    "private_key": re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    "github_token": re.compile(r"\bgh[pousr]_[A-Za-z0-9]{30,}\b"),
    "credential_url": re.compile(r"https?://[^\s/:@]+:[^\s/@]+@[^\s]+"),
    "literal_secret_assignment": re.compile(
        r"(?im)^\s*(?:password|passwd|api_key|apikey|secret|access_token|auth_token)\s*=\s*['\"][^'\"\n]{8,}['\"]"
    ),
}
PRIVACY_PATTERNS = {
    "email": re.compile(r"(?i)\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b"),
    "us_ssn": re.compile(r"\b\d{3}-\d{2}-\d{4}\b"),
    "phone": re.compile(r"(?<!\d)(?:\+?\d[\s().-]*){9,15}(?!\d)"),
}
TOKEN_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*|\d+(?:\.\d+)?|==|!=|<=|>=|:=|->|\S")


def fail(message: str) -> None:
    raise SystemExit(f"NEXT100-049 FAIL: {message}")


def load_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001 - fail closed with context
        fail(f"cannot load {path}: {exc}")


def fetch_raw(repo: str, commit: str, path: str) -> bytes:
    url = f"https://raw.githubusercontent.com/{repo}/{commit}/{path}"
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=30) as response:
            if response.status != 200:
                fail(f"HTTP {response.status} for {url}")
            data = response.read()
    except (urllib.error.URLError, TimeoutError) as exc:
        fail(f"acquisition failed for {url}: {exc}")
    return data


def git_blob_sha1(data: bytes) -> str:
    header = f"blob {len(data)}\0".encode("ascii")
    return hashlib.sha1(header + data).hexdigest()  # noqa: S324 - Git object identity


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def tokens(text: str) -> list[str]:
    return [token.lower() for token in TOKEN_RE.findall(text)]


def shingles(text: str, width: int = 5) -> set[tuple[str, ...]]:
    seq = tokens(text)
    if len(seq) < width:
        return {tuple(seq)} if seq else set()
    return {tuple(seq[i : i + width]) for i in range(len(seq) - width + 1)}


def jaccard(a: set[tuple[str, ...]], b: set[tuple[str, ...]]) -> float:
    if not a and not b:
        return 1.0
    union = a | b
    return len(a & b) / len(union) if union else 0.0


def walk_strings(value):
    if isinstance(value, dict):
        for item in value.values():
            yield from walk_strings(item)
    elif isinstance(value, list):
        for item in value:
            yield from walk_strings(item)
    elif isinstance(value, str):
        yield value


def source_quality(path: str, text: str) -> dict:
    try:
        tree = ast.parse(text, filename=path)
    except SyntaxError as exc:
        fail(f"Python AST parse failed for {path}: {exc}")
    nodes = list(ast.walk(tree))
    definitions = sum(isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) for n in nodes)
    logic_nodes = sum(
        isinstance(
            n,
            (
                ast.Assign,
                ast.AnnAssign,
                ast.AugAssign,
                ast.Call,
                ast.Compare,
                ast.For,
                ast.If,
                ast.Return,
                ast.Try,
                ast.While,
                ast.With,
            ),
        )
        for n in nodes
    )
    if definitions < 1 or logic_nodes < 5 or len(nodes) < 20:
        fail(f"insufficient substantive Python logic in {path}")
    return {
        "ast_node_count": len(nodes),
        "definition_count": definitions,
        "logic_node_count": logic_nodes,
    }


def scan_eval_reservations(config: dict, computed_sha256: list[str]) -> list[str]:
    needles = {
        config["upstream"]["repository_family"],
        config["upstream"]["commit"],
        *computed_sha256,
        *(row["git_blob_sha1"] for row in config["selected_files"]),
        *(row["path"] for row in config["selected_files"]),
    }
    hits: list[str] = []
    interesting = ("eval", "final", "reserv", "benchmark", "selection")
    ignored = {".git", ".venv", "venv", "__pycache__"}
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [name for name in dirnames if name not in ignored]
        for filename in filenames:
            path = Path(dirpath) / filename
            rel = path.relative_to(ROOT).as_posix()
            low = rel.lower()
            if not any(marker in low for marker in interesting):
                continue
            try:
                if path.stat().st_size > 2_000_000:
                    continue
                text = path.read_text(encoding="utf-8")
            except (UnicodeDecodeError, OSError):
                continue
            matched = sorted(needle for needle in needles if needle and needle in text)
            if matched:
                hits.append(f"{rel}:{','.join(matched)}")
    return hits


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    config = load_json(CONFIG_PATH)
    registry = load_json(REGISTRY_PATH)

    if config.get("worker_id") != "NEXT100-049-CODE-NUMPY":
        fail("worker identity drift")
    if config.get("local_free_only") is not True or config.get("training_executed") is not False:
        fail("execution boundary drift")
    expected_registry = config["registry_comparison"]["registry_identity_sha256"]
    if registry.get("registry_identity_sha256") != expected_registry:
        fail("bound DATA-287 registry identity drift")
    if registry.get("claim_boundary", {}).get("evaluation_authorized_source_count") != 0:
        fail("bound registry unexpectedly contains evaluation-authorized source objects")

    upstream = config["upstream"]
    if upstream["canonical_repository"] != "https://github.com/numpy/numpy":
        fail("canonical upstream drift")
    if upstream["repository_family"] != "github:numpy/numpy":
        fail("family identity drift")
    if len(config["selected_files"]) != config["selection_contract"]["file_count"]:
        fail("selected file count mismatch")
    if sum(row["raw_bytes"] for row in config["selected_files"]) != config["selection_contract"]["unique_training_capacity_bytes"]:
        fail("capacity byte accounting mismatch")

    commit = upstream["commit"]
    repo_slug = "numpy/numpy"

    license_cfg = upstream["license"]
    license_bytes = fetch_raw(repo_slug, commit, license_cfg["path"])
    if len(license_bytes) != license_cfg["raw_bytes"]:
        fail("license byte-size drift")
    if git_blob_sha1(license_bytes) != license_cfg["git_blob_sha1"]:
        fail("license Git blob mismatch")
    license_text = license_bytes.decode("utf-8", errors="strict")
    required_license_phrases = (
        "Redistribution and use in source and binary forms, with or without",
        "modification, are permitted provided that the following conditions",
        "Neither the name of the NumPy Developers nor the names of any",
        "THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS",
    )
    if not all(phrase in license_text for phrase in required_license_phrases):
        fail("BSD-3-Clause rights text did not match required grant/conditions")

    registry_strings = set(walk_strings(registry))
    incumbent_families = {
        source["independent_source_family"]["family_id"]
        for source in registry.get("sources", [])
        if isinstance(source, dict) and source.get("independent_source_family")
    }
    if upstream["repository_family"] in incumbent_families:
        fail("NumPy family already exists in bound registry")

    selected_reports = []
    selected_texts: dict[str, str] = {}
    selected_sha256: list[str] = []
    selected_blobs: set[str] = set()
    selected_hashes: set[str] = set()

    for row in config["selected_files"]:
        path = row["path"]
        norm_path = "/" + path.strip("/") + "/"
        if not path.startswith("numpy/_core/") or not path.endswith(".py"):
            fail(f"out-of-scope path: {path}")
        if any(part in norm_path.lower() for part in FORBIDDEN_PATH_PARTS):
            fail(f"forbidden path class selected: {path}")
        data = fetch_raw(repo_slug, commit, path)
        if len(data) != row["raw_bytes"]:
            fail(f"byte-size drift: {path}")
        blob = git_blob_sha1(data)
        if blob != row["git_blob_sha1"]:
            fail(f"Git blob mismatch: {path}")
        if b"\x00" in data:
            fail(f"NUL/binary content: {path}")
        try:
            text = data.decode("utf-8", errors="strict")
        except UnicodeDecodeError as exc:
            fail(f"non-UTF8 source {path}: {exc}")
        prefix = text[:4096].lower()
        marker_hits = [marker for marker in GENERATED_MARKERS if marker in prefix]
        if marker_hits:
            fail(f"generated-code marker in {path}: {marker_hits}")
        secret_hits = [name for name, pattern in SECRET_PATTERNS.items() if pattern.search(text)]
        privacy_hits = [name for name, pattern in PRIVACY_PATTERNS.items() if pattern.search(text)]
        if secret_hits:
            fail(f"secret scan matched {path}: {secret_hits}")
        if privacy_hits:
            fail(f"privacy scan matched {path}: {privacy_hits}")
        quality = source_quality(path, text)
        digest = sha256(data)
        if digest in selected_hashes:
            fail(f"internal exact SHA-256 duplicate: {path}")
        if blob in selected_blobs:
            fail(f"internal exact Git blob duplicate: {path}")
        if digest in registry_strings or blob in registry_strings:
            fail(f"exact collision with bound live registry: {path}")
        selected_hashes.add(digest)
        selected_blobs.add(blob)
        selected_sha256.append(digest)
        selected_texts[path] = text
        selected_reports.append(
            {
                "path": path,
                "raw_bytes": len(data),
                "git_blob_sha1": blob,
                "raw_sha256": digest,
                "normalized_bytes": len(data),
                "normalized_sha256": digest,
                "normalization_policy": "STRICT_UTF8_IDENTITY_PRESERVE_V1",
                "secret_scan": "PASS",
                "privacy_scan": "PASS",
                "python_ast_parse": "PASS",
                "generated_marker_scan": "PASS",
                "quality": quality,
            }
        )

    threshold = float(config["dedup"]["token_5_shingle_jaccard_threshold"])
    internal_pairs = []
    selected_items = list(selected_texts.items())
    for i, (path_a, text_a) in enumerate(selected_items):
        for path_b, text_b in selected_items[i + 1 :]:
            score = jaccard(shingles(text_a), shingles(text_b))
            if score >= threshold:
                fail(f"internal near-duplicate at/above threshold: {path_a} vs {path_b}: {score}")
            internal_pairs.append({"a": path_a, "b": path_b, "jaccard_5": round(score, 12)})

    incumbent_pairs = []
    for incumbent in registry.get("sources", []):
        if incumbent.get("modality") != "code":
            continue
        exact = incumbent.get("exact_upstream_identity", {})
        canonical = exact.get("canonical_repository")
        incumbent_commit = exact.get("commit")
        incumbent_path = exact.get("path")
        if not canonical or not incumbent_commit or not incumbent_path:
            fail("incumbent code source lacks exact upstream identity")
        incumbent_slug = canonical.removeprefix("https://github.com/").strip("/")
        incumbent_bytes = fetch_raw(incumbent_slug, incumbent_commit, incumbent_path)
        incumbent_digest = sha256(incumbent_bytes)
        if incumbent_digest != incumbent["snapshot"]["raw_sha256"]:
            fail(f"incumbent registry raw hash no longer reacquires: {incumbent['source_id']}")
        incumbent_text = incumbent_bytes.decode("utf-8", errors="strict")
        inc_shingles = shingles(incumbent_text)
        for selected_path, selected_text in selected_items:
            score = jaccard(shingles(selected_text), inc_shingles)
            if score >= threshold:
                fail(
                    f"cross-source near-duplicate at/above threshold: {selected_path} vs "
                    f"{incumbent['source_id']}: {score}"
                )
            incumbent_pairs.append(
                {
                    "selected": selected_path,
                    "incumbent": incumbent["source_id"],
                    "jaccard_5": round(score, 12),
                }
            )

    reservation_hits = scan_eval_reservations(config, selected_sha256)
    if reservation_hits:
        fail(f"evaluation/final/selection reservation collision: {reservation_hits}")

    report = {
        "schema_version": "12-6.next100-049.numpy-source-report.v1",
        "worker_id": config["worker_id"],
        "verdict": "ADMIT",
        "upstream": {
            "repository": upstream["canonical_repository"],
            "commit": commit,
            "license_path": license_cfg["path"],
            "license_git_blob_sha1": license_cfg["git_blob_sha1"],
            "license_raw_sha256": sha256(license_bytes),
            "license": "BSD-3-Clause",
        },
        "rights": config["rights"],
        "registry_comparison": config["registry_comparison"],
        "selected_files": selected_reports,
        "capacity": {
            "selected_file_count": len(selected_reports),
            "unique_training_capacity_bytes": sum(item["raw_bytes"] for item in selected_reports),
            "generated_capacity_bytes": 0,
            "binary_capacity_bytes": 0,
            "evaluation_capacity_bytes": 0,
        },
        "dedup": {
            "threshold": threshold,
            "internal_pairs": internal_pairs,
            "incumbent_code_pairs": incumbent_pairs,
            "exact_registry_collision_count": 0,
            "internal_exact_duplicate_count": 0,
        },
        "family": {
            "family_id": upstream["repository_family"],
            "family_identity_sha256": sha256(upstream["repository_family"].encode("utf-8")),
            "independent_source_family_credit": 1,
            "mirror": False,
            "fork": False,
        },
        "evaluation_separation": {
            "reservation_hits": [],
            "status": "NOT_SEPARATELY_ADMITTED",
            "final_test_material_consumed": False,
        },
        "claims": {
            "human_authored_first_party_python_subset": True,
            "generated_c_output_consumed": False,
            "representative_corpus_claimed": False,
            "training_executed": False,
            "registry_mutated": False,
            "local_free_only": True,
        },
    }
    serialized = json.dumps(report, ensure_ascii=False, sort_keys=True, indent=2) + "\n"
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(serialized, encoding="utf-8")
    print(serialized, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
