#!/usr/bin/env python3
"""Exact, fail-closed Rich source qualification for NEXT100-051.

GitHub API metadata calls use the Actions token when available. Immutable raw
objects remain pinned by exact commit, Git blob, byte size and SHA-256 checks.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
import re
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any

WORKER = "NEXT100-051-CODE-RICH"
SCHEMA = "12-6.next100-051-rich-source-admission.v1"
DATA227_HEAD = "8ebdb2e132ed7bae5245e9d4c140752640ab9885"
DATA287_HEAD = "b0523ccbc4b957615aac849d476cfa851be87578"
DATA287_REGISTRY_ID = "917e9bc31b2fa040d25e807ae3c01aa2cce32420752a891caacfb6c830e6632c"
EVAL289_HEAD = "1c870e5e02bf48891ca599b0b3f3bfe6e84425bc"
UPSTREAM_COMMIT = "6ac483cbea39cab124dfd3483bba70ffafb71050"
UPSTREAM_TREE = "3b564e8788a0dec98e2a9f6558ee978ce00689a0"
LICENSE_BLOB = "4415505566f261c802b671426be529a31f914137"
LICENSE_SHA256 = "deed7c17a4318158190a3ea239cc879a5a50271cebb98ae7025f48fbe58dca15"
NEAR_THRESHOLD = 0.85
SHINGLE_SIZE = 5

SECRET_PATTERNS = (
    re.compile(rb"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(rb"\bgh[pousr]_[A-Za-z0-9_]{20,}\b"),
    re.compile(rb"\bsk-[A-Za-z0-9_-]{20,}\b"),
    re.compile(rb"\bAKIA[0-9A-Z]{16}\b"),
    re.compile(rb"\bAIza[0-9A-Za-z_-]{30,}\b"),
)
PRIVACY_CREDENTIAL_PATTERNS = (
    re.compile(rb"(?i)https?://[^/\s:@]+:[^/\s@]+@"),
    re.compile(
        rb"(?i)\b(?:password|passwd|api[_-]?key|secret|access[_-]?token)\s*=\s*['\"][A-Za-z0-9_+./=-]{20,}['\"]"
    ),
    re.compile(rb"(?i)\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b"),
    re.compile(rb"\b\d{3}-\d{2}-\d{4}\b"),
)
GENERATED_PATTERNS = (
    re.compile(r"(?i)\bcode generated\b.{0,120}\bdo not edit\b"),
    re.compile(r"(?i)<auto-generated(?:\s|>)"),
    re.compile(r"(?i)\bautomatically generated\b"),
    re.compile(r"(?i)\bthis file (?:is|was) generated\b"),
    re.compile(r"(?i)(?:^|\s)@generated(?:\s|$)"),
)
FORBIDDEN_SELECTED_NAMES = {"_emoji_codes.py", "_spinners.py", "_palettes.py"}


class QualificationError(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise QualificationError(message)


def git_blob_sha1(data: bytes) -> str:
    return hashlib.sha1(f"blob {len(data)}\0".encode("ascii") + data).hexdigest()  # noqa: S324


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _headers(url: str) -> dict[str, str]:
    headers = {"User-Agent": "12-6-NEXT100-051-Rich/2"}
    host = urllib.parse.urlparse(url).hostname
    token = os.environ.get("GITHUB_TOKEN")
    if token and host == "api.github.com":
        headers.update(
            {
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
            }
        )
    return headers


def download(url: str, max_bytes: int = 350_000) -> bytes:
    request = urllib.request.Request(url, headers=_headers(url))
    try:
        with urllib.request.urlopen(request, timeout=45) as response:
            data = response.read(max_bytes + 1)
    except Exception as exc:
        raise QualificationError(f"download failed for {url}: {exc}") from exc
    require(len(data) <= max_bytes, f"bounded download exceeded {max_bytes}: {url}")
    return data


def load_json(url: str, max_bytes: int = 200_000) -> dict[str, Any]:
    try:
        value = json.loads(download(url, max_bytes).decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise QualificationError(f"invalid JSON from {url}: {exc}") from exc
    require(isinstance(value, dict), f"JSON root is not an object: {url}")
    return value


def token_shingles(text: str) -> set[tuple[str, ...]]:
    tokens = re.findall(r"[A-Za-z_][A-Za-z0-9_]*|\d+|[^\s]", text.casefold())
    if len(tokens) < SHINGLE_SIZE:
        return set()
    return {
        tuple(tokens[i : i + SHINGLE_SIZE])
        for i in range(len(tokens) - SHINGLE_SIZE + 1)
    }


def near_jaccard(left: str, right: str) -> float:
    a, b = token_shingles(left), token_shingles(right)
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def qualify(*, repo_root: Path, policy_path: Path, source_sha: str) -> dict[str, Any]:
    policy = json.loads((repo_root / policy_path).read_text(encoding="utf-8"))
    require(policy["schema_version"] == "12-6.next100-051-rich-code-rights.v1", "policy schema drift")
    require(policy["worker_id"] == WORKER, "worker drift")
    require(policy["policy_ref"] == "policy://12-6/data/explicit-model-training-evidence-v1", "policy purpose drift")
    require(policy["source_family"] == "github:Textualize/rich", "family drift")
    require(policy["canonical_repository_id"] == 220809393, "repository id drift")
    require(policy["upstream_tag"] == "v15.0.0", "tag drift")
    require(policy["upstream_commit"] == UPSTREAM_COMMIT, "commit drift")
    require(policy["upstream_tree"] == UPSTREAM_TREE, "tree drift")
    require(policy["license"]["blob_sha1"] == LICENSE_BLOB, "license blob drift")
    require(policy["license"]["sha256"] == LICENSE_SHA256, "license SHA drift")
    decisions = policy["decisions"]
    require(len(decisions) == 6, "expected six bounded Rich objects")
    require(sum(int(row["size_bytes"]) for row in decisions) == 46_162, "capacity drift")
    require(all(row["capacity_counted"] is True for row in decisions), "non-counted object selected")
    require(all(row["authorship_class"] == "UPSTREAM_AUTHORED_IMPLEMENTATION" for row in decisions), "authorship drift")
    require(policy["uses"]["evaluation"] == "NOT_SEPARATELY_ADMITTED", "evaluation boundary drift")

    repo_meta = load_json("https://api.github.com/repos/Textualize/rich")
    require(repo_meta["id"] == 220809393, "upstream repository id drift")
    require(repo_meta["html_url"] == "https://github.com/Textualize/rich", "upstream URL drift")
    require(repo_meta["fork"] is False and repo_meta["mirror_url"] is None, "upstream is fork/mirror")
    tag_ref = load_json("https://api.github.com/repos/Textualize/rich/git/ref/tags/v15.0.0")
    require(tag_ref["object"]["type"] == "commit", "Rich tag type drift")
    require(tag_ref["object"]["sha"] == UPSTREAM_COMMIT, "Rich tag commit drift")
    upstream_commit = load_json(f"https://api.github.com/repos/Textualize/rich/git/commits/{UPSTREAM_COMMIT}")
    require(upstream_commit["tree"]["sha"] == UPSTREAM_TREE, "Rich tree drift")

    license_bytes = download(policy["license"]["url"])
    require(len(license_bytes) == policy["license"]["size_bytes"], "license size drift")
    require(git_blob_sha1(license_bytes) == LICENSE_BLOB, "license Git blob drift")
    require(sha256(license_bytes) == LICENSE_SHA256, "license SHA-256 drift")
    license_text = license_bytes.decode("utf-8", errors="strict")
    for phrase in (
        "deal in the Software without restriction",
        "use, copy, modify, merge, publish, distribute, sublicense, and/or sell",
        "copyright notice and this permission notice shall be included",
        'THE SOFTWARE IS PROVIDED "AS IS"',
    ):
        require(phrase in license_text, f"MIT phrase missing: {phrase}")

    objects: list[dict[str, Any]] = []
    texts: dict[str, str] = {}
    raw_hashes: set[str] = set()
    for decision in decisions:
        path = decision["path"]
        require(path.startswith("rich/") and path.endswith(".py"), f"{path}: path boundary")
        require("/tests/" not in f"/{path}" and "/examples/" not in f"/{path}", f"{path}: test/example selected")
        require(Path(path).name not in FORBIDDEN_SELECTED_NAMES, f"{path}: generated table selected")
        require("_unicode_data/" not in path, f"{path}: unicode table selected")
        raw = download(decision["raw_url"])
        require(len(raw) == decision["size_bytes"], f"{decision['source_id']}: size drift")
        require(git_blob_sha1(raw) == decision["blob_sha1"], f"{decision['source_id']}: Git blob drift")
        require(b"\x00" not in raw, f"{decision['source_id']}: NUL byte")
        text = raw.decode("utf-8", errors="strict")
        require("\ufffd" not in text, f"{decision['source_id']}: replacement char")
        require(not any(0xD800 <= ord(ch) <= 0xDFFF for ch in text), f"{decision['source_id']}: surrogate")
        require(not any(pattern.search(text[:8192]) for pattern in GENERATED_PATTERNS), f"{decision['source_id']}: generated marker")
        require(not any(pattern.search(raw) for pattern in SECRET_PATTERNS), f"{decision['source_id']}: secret pattern")
        require(not any(pattern.search(raw) for pattern in PRIVACY_CREDENTIAL_PATTERNS), f"{decision['source_id']}: privacy/credential pattern")
        tree = ast.parse(text, filename=path)
        compile(tree, path, "exec")
        definitions = sum(
            isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
            for node in ast.walk(tree)
        )
        nonblank_lines = sum(bool(line.strip()) for line in text.splitlines())
        require(definitions >= 1, f"{decision['source_id']}: no definitions")
        require(nonblank_lines >= 40, f"{decision['source_id']}: too little substantive code")
        raw_sha = sha256(raw)
        require(raw_sha not in raw_hashes, f"{decision['source_id']}: exact duplicate")
        raw_hashes.add(raw_sha)
        objects.append(
            {
                "source_id": decision["source_id"],
                "source_family": decision["source_family"],
                "commit": decision["commit"],
                "path": path,
                "git_blob_sha1": decision["blob_sha1"],
                "size_bytes": len(raw),
                "raw_sha256": raw_sha,
                "normalized_sha256": raw_sha,
                "normalization_policy": "STRICT_UTF8_IDENTITY_PRESERVE_V1",
                "parse_validity": "PASS_AST_PARSE_AND_COMPILE_PY311",
                "quality": {
                    "nonblank_lines": nonblank_lines,
                    "definition_count": definitions,
                    "substantive_implementation": True,
                },
                "secret_scan": "PASS_SUPPORTED_CREDENTIAL_PATTERNS",
                "privacy_scan": "PASS_NO_EMAIL_SSN_OR_CREDENTIAL_BEARING_LITERAL_PATTERN",
                "generated_material": False,
                "authorship_class": decision["authorship_class"],
                "capacity_counted": True,
                "training_purpose_decision": "ALLOWED",
                "redistribution_decision": "ALLOWED_WITH_MIT_NOTICE",
                "evaluation_use": "NOT_ADMITTED",
            }
        )
        texts[decision["source_id"]] = text

    prior_policy = json.loads((repo_root / "configs/data/data227_code_rights_policy_v1.json").read_text(encoding="utf-8"))
    prior_families = sorted({row["source_family"] for row in prior_policy["decisions"]})
    require(prior_families == ["github:encode/httpx", "github:psf/requests"], "DATA-227 family drift")
    comparison_texts = dict(texts)
    prior_raw_hashes: set[str] = set()
    for prior in prior_policy["decisions"]:
        raw = download(prior["raw_url"])
        require(len(raw) == prior["size_bytes"], f"{prior['source_id']}: DATA-227 size drift")
        require(git_blob_sha1(raw) == prior["blob_sha1"], f"{prior['source_id']}: DATA-227 blob drift")
        prior_raw_hashes.add(sha256(raw))
        comparison_texts[prior["source_id"]] = raw.decode("utf-8", errors="strict")
    require(not (raw_hashes & prior_raw_hashes), "exact overlap with DATA-227")

    registry = load_json(
        "https://raw.githubusercontent.com/Oleksii-debug/12-6-ai./"
        + DATA287_HEAD
        + "/data/registry/external_snapshots.v2.json"
    )
    require(registry["registry_identity_sha256"] == DATA287_REGISTRY_ID, "DATA-287 registry identity drift")
    registry_code = [row for row in registry["sources"] if row["modality"] == "code"]
    registry_families = sorted(
        row["independent_source_family"]["family_id"] for row in registry_code
    )
    require(registry_families == prior_families, "DATA-287 code families drift")
    registry_raw_hashes = {row["snapshot"]["raw_sha256"] for row in registry_code}
    require(not (raw_hashes & registry_raw_hashes), "exact overlap with DATA-287")
    require(
        policy["source_family"]
        not in {row["independent_source_family"]["family_id"] for row in registry["sources"]},
        "Rich family already registered",
    )

    near_pairs: list[dict[str, Any]] = []
    max_pair: list[str] | None = None
    max_score = -1.0
    ids = sorted(comparison_texts)
    for index, left in enumerate(ids):
        for right in ids[index + 1 :]:
            score = near_jaccard(comparison_texts[left], comparison_texts[right])
            if score > max_score:
                max_score = score
                max_pair = [left, right]
            if score >= NEAR_THRESHOLD:
                near_pairs.append({"left": left, "right": right, "jaccard": score})
    require(not near_pairs, "near-duplicate threshold violated")

    eval289 = load_json(
        "https://raw.githubusercontent.com/Oleksii-debug/12-6-ai./"
        + EVAL289_HEAD
        + "/evidence/eval289/code-evaluation-rights-reservation.json"
    )
    require(eval289["reservation"]["active"] is False, "evaluation reservation became active")
    require(eval289["reservation"]["objects"] == [], "reserved evaluation objects exist")

    core: dict[str, Any] = {
        "schema_version": SCHEMA,
        "worker_id": WORKER,
        "status": "ADMIT",
        "authority": "EXTERNAL_REAL_CODE_SOURCE_TERMINAL_LOCAL_FREE",
        "worker_source_sha": source_sha,
        "predecessor_code_authority": {
            "data227_head_sha": DATA227_HEAD,
            "policy_git_blob_sha1": "0ce5223a1cade10031899bf27348a1a65121d4c6",
            "source_family_count": 2,
            "source_families": prior_families,
        },
        "registry_binding": {
            "data287_head_sha": DATA287_HEAD,
            "registry_identity_sha256": DATA287_REGISTRY_ID,
            "terminal_code_family_count": len(registry_code),
            "selected_exact_hash_overlap": False,
            "selected_family_collision": False,
        },
        "upstream": {
            "repository": "https://github.com/Textualize/rich",
            "repository_id": 220809393,
            "tag": "v15.0.0",
            "tag_object_type": "commit",
            "commit": UPSTREAM_COMMIT,
            "tree": UPSTREAM_TREE,
            "repository_fork": False,
            "repository_mirror": False,
        },
        "license": {
            "license_id": "MIT",
            "path": "LICENSE",
            "git_blob_sha1": LICENSE_BLOB,
            "sha256": LICENSE_SHA256,
            "model_training": "ALLOWED_BY_REVIEWED_MIT_GRANT",
            "derivatives": "ALLOWED",
            "redistribution": "ALLOWED_WITH_NOTICE",
            "notice_required": True,
        },
        "objects": objects,
        "checks": {
            "strict_utf8_identity_normalization": "PASS",
            "parse_validity": "PASS_6_OF_6_AST_AND_COMPILE",
            "quality": "PASS_6_OF_6_SUBSTANTIVE_IMPLEMENTATION",
            "secret_privacy": "PASS_6_OF_6",
            "generated_selected_count": 0,
            "generated_selected_bytes": 0,
            "examples_selected_count": 0,
            "evaluation_fixtures_selected_count": 0,
            "exact_duplicate_sha256": [],
            "predecessor_exact_overlap": False,
            "registry_exact_overlap": False,
            "near_duplicate_threshold": NEAR_THRESHOLD,
            "near_duplicate_pairs": near_pairs,
            "max_observed_pair": max_pair,
            "max_observed_jaccard": max_score,
            "current_eval_reservation_active_at_eval289_head": False,
        },
        "source_family_accounting": {
            "new_source_family": policy["source_family"],
            "canonical_repository_id": 220809393,
            "independent_new_family_count": 1,
            "predecessor_code_family_count": 2,
            "resulting_code_family_count_if_registered": 3,
            "selected_implementation_object_count": 6,
            "selected_authored_capacity_bytes": 46_162,
            "generated_capacity_bytes": 0,
            "generated_capacity_objects": 0,
        },
        "excluded_capacity": policy["excluded_capacity"],
        "evaluation_boundary": {
            "eval289_head_sha": EVAL289_HEAD,
            "active_reserved_objects": 0,
            "selected_objects_overlap_active_reservation": False,
            "evaluation_use": "NOT_ADMITTED",
        },
        "execution": {
            "class": "LOCAL_FREE",
            "paid_compute_used": False,
            "model_training_executed": False,
            "optimizer_updates": 0,
            "network_use": "bounded immutable-source qualification only",
            "github_api_authenticated": bool(os.environ.get("GITHUB_TOKEN")),
        },
        "terminal_decision": (
            "ADMIT exact six-object Rich v15.0.0 implementation snapshot for training-source registration; "
            "examples, tests, docs, known generated tables, vendored/binary/build material and evaluation-purpose objects remain excluded."
        ),
    }
    canonical = (
        json.dumps(core, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n"
    ).encode("utf-8")
    return {**core, "authority_identity_sha256": sha256(canonical)}


def verify_evidence(value: dict[str, Any]) -> None:
    supplied = value.get("authority_identity_sha256")
    unsigned = dict(value)
    unsigned.pop("authority_identity_sha256", None)
    canonical = (
        json.dumps(unsigned, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n"
    ).encode("utf-8")
    require(supplied == sha256(canonical), "authority self-hash mismatch")
    require(value.get("status") == "ADMIT", "terminal status is not ADMIT")
    require(value["source_family_accounting"]["selected_implementation_object_count"] == 6, "object-count drift")
    require(value["source_family_accounting"]["selected_authored_capacity_bytes"] == 46_162, "capacity drift")
    require(value["execution"]["class"] == "LOCAL_FREE", "execution class drift")
    require(value["execution"]["paid_compute_used"] is False, "paid compute used")
    require(value["execution"]["model_training_executed"] is False, "model training executed")
    require(value["execution"]["optimizer_updates"] == 0, "optimizer updates executed")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path("."))
    parser.add_argument(
        "--policy",
        type=Path,
        default=Path("configs/data/next100_051_rich_code_rights_v1.json"),
    )
    parser.add_argument("--source-sha", default=os.environ.get("EXPECTED_SOURCE_SHA", ""))
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    require(len(args.source_sha) == 40, "exact worker source SHA is required")
    evidence = qualify(
        repo_root=args.repo_root.resolve(),
        policy_path=args.policy,
        source_sha=args.source_sha,
    )
    verify_evidence(evidence)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(evidence, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n",
        encoding="utf-8",
    )
    print(
        json.dumps(
            {
                "status": evidence["status"],
                "capacity_bytes": evidence["source_family_accounting"]["selected_authored_capacity_bytes"],
                "authority_identity_sha256": evidence["authority_identity_sha256"],
                "github_api_authenticated": evidence["execution"]["github_api_authenticated"],
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
