#!/usr/bin/env python3
"""NEXT100-046 bounded Click admission verifier (stdlib-only, LOCAL_FREE)."""
from __future__ import annotations

import argparse, ast, datetime as dt, hashlib, ipaddress, json, os, re, urllib.request
from pathlib import Path

CONFIG = Path("configs/data/next100_046_click_code_source_v1.json")
UA = "12-6-NEXT100-046-Click/1"
TOKEN = re.compile(r"[A-Za-z_][A-Za-z0-9_]*|\d+|[^\s]")
EMAIL = re.compile(r"(?<![A-Za-z0-9._%+-])([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})(?![A-Za-z0-9._%+-])")
IPV4 = re.compile(r"(?<!\d)(?:\d{1,3}\.){3}\d{1,3}(?!\d)")
SECRETS = (
    ("private_key", re.compile(rb"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----")),
    ("github", re.compile(rb"\bgh[pousr]_[A-Za-z0-9_]{20,}\b")),
    ("openai", re.compile(rb"\bsk-[A-Za-z0-9_-]{20,}\b")),
    ("aws", re.compile(rb"\bAKIA[0-9A-Z]{16}\b")),
    ("slack", re.compile(rb"\bxox[baprs]-[A-Za-z0-9-]{20,}\b")),
    ("npm", re.compile(rb"\bnpm_[A-Za-z0-9]{20,}\b")),
    ("jwt", re.compile(rb"\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b")),
)
SAFE_EMAIL = {"example.com", "example.org", "example.net"}
GENERATED = ("generated by", "auto-generated", "autogenerated", "do not edit")


class GateError(RuntimeError):
    pass


def get(url: str, limit: int = 2_500_000) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA, "Accept": "application/vnd.github+json"})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = r.read(limit + 1)
    if len(data) > limit:
        raise GateError(f"download exceeded bound: {url}")
    return data


def jget(url: str, limit: int = 2_500_000):
    return json.loads(get(url, limit))


def gitsha(data: bytes) -> str:
    return hashlib.sha1(f"blob {len(data)}\0".encode() + data).hexdigest()


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def raw_url(repo: str, commit: str, path: str) -> str:
    return f"https://raw.githubusercontent.com/{repo.removeprefix('https://github.com/').strip('/')}/{commit}/{path}"


def shingles(text: str, n: int):
    t = TOKEN.findall(text.casefold())
    return {tuple(t[i:i+n]) for i in range(len(t)-n+1)} if len(t) >= n else set()


def sim(a: str, b: str, n: int):
    x, y = shingles(a, n), shingles(b, n)
    if not x or not y:
        return 0.0, 0.0
    inter = len(x & y)
    return inter / len(x | y), inter / min(len(x), len(y))


def scan(raw: bytes, text: str, path: str):
    hits = [name for name, pat in SECRETS if pat.search(raw)]
    if hits:
        raise GateError(f"{path}: secret-like hits {hits}")
    emails = sorted(set(EMAIL.findall(text)))
    bad_emails = [x for x in emails if x.rsplit("@", 1)[1].casefold() not in SAFE_EMAIL]
    if bad_emails:
        raise GateError(f"{path}: non-example email-like material {bad_emails}")
    private = []
    for x in sorted(set(IPV4.findall(text))):
        try:
            ip = ipaddress.ip_address(x)
        except ValueError:
            continue
        if ip.is_private and not ip.is_loopback:
            private.append(x)
    if private:
        raise GateError(f"{path}: private-network endpoint-like material {private}")
    return {"secret_hits": [], "email_like_count": len(emails), "private_ip_count": 0}


def quality(raw: bytes, text: str, path: str):
    markers = [m for m in GENERATED if m in text[:2048].casefold()]
    if markers:
        raise GateError(f"{path}: generated-code marker {markers}")
    try:
        tree = ast.parse(text, filename=path)
        compile(text, path, "exec", dont_inherit=True, optimize=0)
    except SyntaxError as e:
        raise GateError(f"{path}: parse/compile failed: {e}") from e
    nodes = sum(1 for _ in ast.walk(tree))
    defs = sum(isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) for n in ast.walk(tree))
    code_lines = sum(1 for line in text.splitlines() if line.strip() and not line.lstrip().startswith("#"))
    if len(raw) < 5000 or code_lines < 40 or nodes < 100 or defs < 3:
        raise GateError(f"{path}: weak implementation bytes={len(raw)} lines={code_lines} nodes={nodes} defs={defs}")
    return {"ast": True, "compile": True, "utf8_identity": True, "code_lines": code_lines, "ast_nodes": nodes, "defs": defs}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", type=Path, default=Path("."))
    ap.add_argument("--output", type=Path, required=True)
    a = ap.parse_args()
    cfg = json.loads((a.repo / CONFIG).read_text(encoding="utf-8"))
    if cfg["schema_version"] != "12-6.next100-046-click-code-source.v1":
        raise GateError("schema drift")
    if cfg["execution_profile"] != "LOCAL_FREE" or os.getenv("TWELVE_SIX_EXECUTION_PROFILE", "LOCAL_FREE") != "LOCAL_FREE":
        raise GateError("LOCAL_FREE profile required")
    if cfg["source_family"] != "github:pallets/click" or len(cfg["files"]) != 3:
        raise GateError("bounded family/file-count drift")
    if sum(x["size_bytes"] for x in cfg["files"]) != cfg["capacity_bytes"]:
        raise GateError("capacity declaration drift")

    meta = jget("https://api.github.com/repos/pallets/click", 150000)
    if int(meta["id"]) != cfg["repository_id"] or meta["html_url"] != cfg["repository_url"] or meta.get("fork") is not False or meta.get("mirror_url") is not None:
        raise GateError("canonical upstream repository identity failed")
    ref = jget(f"https://api.github.com/repos/pallets/click/git/ref/tags/{cfg['upstream_release']}", 50000)
    if ref["object"] != {"sha": cfg["tag_object_sha1"], "type": "tag", "url": ref["object"]["url"]}:
        raise GateError("annotated tag identity drift")
    tag = jget(f"https://api.github.com/repos/pallets/click/git/tags/{cfg['tag_object_sha1']}", 100000)
    if tag["object"]["type"] != "commit" or tag["object"]["sha"] != cfg["upstream_commit"]:
        raise GateError("release tag commit drift")
    tree = jget(f"https://api.github.com/repos/pallets/click/git/trees/{cfg['upstream_commit']}?recursive=1")
    by_path = {x["path"]: x for x in tree["tree"]}
    st = by_path.get(cfg["source_tree"]["path"])
    if not st or st["type"] != "tree" or st["sha"] != cfg["source_tree"]["git_tree_sha1"]:
        raise GateError("source tree identity drift")

    lic = cfg["license"]
    lraw = get(lic["raw_url"], 20000)
    if len(lraw) != lic["size_bytes"] or gitsha(lraw) != lic["git_blob_sha1"]:
        raise GateError("license blob identity drift")
    ltext = lraw.decode("utf-8", "strict")
    for phrase in ("Redistribution and use in source and binary forms", "with or without modification", "Neither the name of the copyright holder"):
        if phrase not in ltext:
            raise GateError("license grant text drift")

    objects, texts = [], []
    for item in cfg["files"]:
        path = item["path"]
        if not path.startswith("src/click/") or not path.endswith(".py"):
            raise GateError(f"outside allowlist root: {path}")
        entry = by_path.get(path)
        if not entry or entry["type"] != "blob" or entry["sha"] != item["git_blob_sha1"] or entry["size"] != item["size_bytes"]:
            raise GateError(f"tree identity drift: {path}")
        raw = get(raw_url(cfg["repository_url"], cfg["upstream_commit"], path), 250000)
        if len(raw) != item["size_bytes"] or gitsha(raw) != item["git_blob_sha1"]:
            raise GateError(f"raw/blob identity drift: {path}")
        text = raw.decode("utf-8", "strict")
        if text.encode("utf-8") != raw:
            raise GateError(f"normalization identity failed: {path}")
        obj = {
            "path": path, "role": item["role"], "size_bytes": len(raw), "git_blob_sha1": item["git_blob_sha1"],
            "raw_sha256": sha256(raw), "normalization_sha256": sha256(raw),
            "privacy_secret_scan": scan(raw, text, path), "quality": quality(raw, text, path),
        }
        objects.append(obj)
        texts.append((f"{cfg['source_family']}:{path}", text))

    if len({x["git_blob_sha1"] for x in objects}) != 3 or len({x["raw_sha256"] for x in objects}) != 3:
        raise GateError("exact duplicate inside Click selection")
    n = cfg["verification"]["near_dedup"]["token_shingle_size"]
    jt = cfg["verification"]["near_dedup"]["jaccard_threshold"]
    ct = cfg["verification"]["near_dedup"]["containment_threshold"]
    comparisons, pairs = [], []
    for i, (lid, ltext) in enumerate(texts):
        for rid, rtext in texts[i+1:]:
            pairs.append((lid, ltext, rid, rtext, "within_click"))
    for item in cfg["comparison_objects"]:
        other = get(raw_url(item["repository_url"], item["commit"], item["path"]), 250000)
        if gitsha(other) != item["git_blob_sha1"]:
            raise GateError(f"comparison identity drift: {item['source_family']}:{item['path']}")
        otext = other.decode("utf-8", "strict")
        for lid, ltext in texts:
            pairs.append((lid, ltext, f"{item['source_family']}:{item['path']}", otext, "cross_source"))
    max_j, max_c, max_pair = 0.0, 0.0, None
    for lid, ltext, rid, rtext, scope in pairs:
        j, c = sim(ltext, rtext, n)
        comparisons.append({"left": lid, "right": rid, "scope": scope, "jaccard": round(j, 8), "containment": round(c, 8)})
        if j > max_j or (j == max_j and c > max_c):
            max_j, max_c, max_pair = j, c, [lid, rid]
        if j >= jt or c >= ct:
            raise GateError(f"near duplicate {lid} vs {rid}: j={j:.6f} c={c:.6f}")

    report = {
        "schema_version": "12-6.next100-046-click-code-admission-report.v1",
        "worker_id": cfg["authority_id"],
        "captured_at_utc": dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat(),
        "execution_profile": "LOCAL_FREE",
        "verdict": "ADMIT",
        "source_family": cfg["source_family"],
        "independent_family_credit": 1,
        "upstream_release": cfg["upstream_release"],
        "upstream_commit": cfg["upstream_commit"],
        "repository_id": cfg["repository_id"],
        "source_tree_sha1": cfg["source_tree"]["git_tree_sha1"],
        "license": {
            "spdx": lic["spdx"], "git_blob_sha1": lic["git_blob_sha1"], "raw_sha256": sha256(lraw),
            "size_bytes": len(lraw), "training_use_decision": lic["training_use_decision"],
            "redistribution_decision": lic["redistribution_decision"],
        },
        "training_purpose_decision": cfg["rights_decision"]["model_training"],
        "redistribution_decision": cfg["rights_decision"]["redistribution"],
        "evaluation_use": cfg["rights_decision"]["evaluation_use"],
        "object_count": 3,
        "capacity_bytes": sum(x["size_bytes"] for x in objects),
        "objects": objects,
        "normalization_identity_preserved": True,
        "privacy_secrets_pass": True,
        "syntax_parse_compile_pass": True,
        "quality_pass": True,
        "generated_vendored_capacity_bytes": 0,
        "lineage_exclusions": cfg["lineage_exclusions"],
        "dedup": {
            "exact_duplicates": [], "near_duplicate_pairs": [], "comparison_object_count": len(cfg["comparison_objects"]),
            "comparison_pair_count": len(comparisons), "token_shingle_size": n, "jaccard_threshold": jt,
            "containment_threshold": ct, "max_observed_jaccard": round(max_j, 8),
            "max_observed_containment_for_max_jaccard_pair": round(max_c, 8), "max_similarity_pair": max_pair,
            "comparisons": comparisons,
        },
        "family_policy": cfg["family_policy"],
        "claim_boundary": {
            "whole_repository_admitted": False, "docs_tests_generated_vendored_admitted": False,
            "evaluation_authorized": False, "model_training_executed": False,
            "mutation_rule": "Any repository/release/commit/path/blob/license/rights/lineage/evaluation/live-registry identity change requires a new authority.",
        },
    }
    if report["capacity_bytes"] != cfg["capacity_bytes"]:
        raise GateError("verified capacity mismatch")
    basis = (json.dumps(report, sort_keys=True, separators=(",", ":"), ensure_ascii=False) + "\n").encode()
    report["authority_sha256"] = sha256(basis)
    a.output.parent.mkdir(parents=True, exist_ok=True)
    a.output.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps({"verdict": "ADMIT", "authority_sha256": report["authority_sha256"], "max_jaccard": report["dedup"]["max_observed_jaccard"]}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
