#!/usr/bin/env python3
"""Exact bounded Jinja source admission validator for NEXT100-047.

Stdlib-only, network-bounded, LOCAL_FREE. It acquires only pinned public GitHub
objects, verifies Git blob identities, preserves exact bytes, parses Python,
scans for privacy/secrets, evaluates code quality, and checks exact/near dedup.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import ipaddress
import json
import re
import urllib.request
from pathlib import Path
from typing import Any

CONFIG = Path("configs/data/next100_047_jinja_code_source_v1.json")
REPORT_SCHEMA = "12-6.next100-047-jinja-code-admission-report.v1"
USER_AGENT = "12-6-NEXT100-047-Jinja-admission/1"
MAX_FILE_BYTES = 150_000
NEAR_THRESHOLD = 0.85
SHINGLE_SIZE = 5

SECRET_PATTERNS = (
    ("private_key", re.compile(rb"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----")),
    ("github_token", re.compile(rb"\bgh[pousr]_[A-Za-z0-9_]{20,}\b")),
    ("openai_key", re.compile(rb"\bsk-[A-Za-z0-9_-]{20,}\b")),
    ("aws_access_key", re.compile(rb"\bAKIA[0-9A-Z]{16}\b")),
    ("slack_token", re.compile(rb"\bxox[baprs]-[A-Za-z0-9-]{20,}\b")),
    ("npm_token", re.compile(rb"\bnpm_[A-Za-z0-9]{20,}\b")),
)
EMAIL_RE = re.compile(r"(?<![A-Za-z0-9._%+-])([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})(?![A-Za-z0-9._%+-])")
IPV4_RE = re.compile(r"(?<!\d)(?:\d{1,3}\.){3}\d{1,3}(?!\d)")
TOKEN_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*|\d+|[^\s]")
GENERATED_MARKERS = ("generated by", "auto-generated", "autogenerated", "do not edit")
BANNED_PARTS = {"vendor", "vendored", "third_party", "third-party", "node_modules", "dist", "build", "generated", "gen", "deps", "site-packages"}
SAFE_EMAIL_DOMAINS = {"example.com", "example.org", "example.net"}


class AdmissionError(RuntimeError):
    pass


def cjson(value: object) -> bytes:
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n").encode("utf-8")


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def git_blob_sha1(data: bytes) -> str:
    return hashlib.sha1(f"blob {len(data)}\0".encode("ascii") + data).hexdigest()


def download(url: str, *, max_bytes: int = MAX_FILE_BYTES) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as response:
        data = response.read(max_bytes + 1)
    if len(data) > max_bytes:
        raise AdmissionError(f"bounded download exceeded {max_bytes} bytes: {url}")
    return data


def load_config(repo: Path) -> dict[str, Any]:
    cfg = json.loads((repo / CONFIG).read_bytes())
    if cfg.get("schema_version") != "12-6.next100-047-jinja-code-source.v1":
        raise AdmissionError("unsupported config schema")
    if cfg.get("execution_profile") != "LOCAL_FREE":
        raise AdmissionError("execution profile must remain LOCAL_FREE")
    if cfg.get("source_family") != "github:pallets/jinja":
        raise AdmissionError("unexpected source family")
    if len(cfg.get("files", [])) != 5:
        raise AdmissionError("bounded v1 authority requires exactly five files")
    if sum(item["size_bytes"] for item in cfg["files"]) != cfg["capacity_bytes"]:
        raise AdmissionError("declared capacity does not equal selected implementation bytes")
    return cfg


def verify_repository(cfg: dict[str, Any]) -> dict[str, Any]:
    meta = json.loads(download("https://api.github.com/repos/pallets/jinja", max_bytes=100_000))
    if meta.get("html_url") != cfg["repository_url"]:
        raise AdmissionError("canonical repository identity drift")
    if meta.get("fork") is not False:
        raise AdmissionError("fork repositories cannot define the independent family")
    if meta.get("mirror_url") is not None:
        raise AdmissionError("mirror repositories cannot define the independent family")
    return {
        "html_url": meta.get("html_url"),
        "fork": meta.get("fork"),
        "mirror_url": meta.get("mirror_url"),
        "archived": meta.get("archived"),
    }


def assert_path_allowed(path: str) -> None:
    p = Path(path)
    if p.suffix != ".py":
        raise AdmissionError(f"non-Python capacity path excluded: {path}")
    parts = {part.casefold() for part in p.parts}
    if parts & BANNED_PARTS:
        raise AdmissionError(f"vendored/generated/build path excluded: {path}")
    if not path.startswith("src/jinja2/"):
        raise AdmissionError(f"outside implementation root: {path}")


def scan_secret_privacy(raw: bytes, text: str, path: str) -> dict[str, Any]:
    secret_hits = [name for name, pattern in SECRET_PATTERNS if pattern.search(raw)]
    if secret_hits:
        raise AdmissionError(f"{path}: secret-like material: {secret_hits}")

    emails = sorted(set(EMAIL_RE.findall(text)))
    unsafe_emails = [email for email in emails if email.rsplit("@", 1)[-1].casefold() not in SAFE_EMAIL_DOMAINS]
    if unsafe_emails:
        raise AdmissionError(f"{path}: non-example email-like material: {unsafe_emails}")

    private_ips: list[str] = []
    for candidate in sorted(set(IPV4_RE.findall(text))):
        try:
            ip = ipaddress.ip_address(candidate)
        except ValueError:
            continue
        if ip.is_private and not ip.is_loopback:
            private_ips.append(candidate)
    if private_ips:
        raise AdmissionError(f"{path}: private-network endpoint-like material: {private_ips}")

    return {
        "secret_hits": [],
        "email_like_count": len(emails),
        "non_example_email_count": 0,
        "private_ip_count": 0,
    }


def quality_and_parse(text: str, raw: bytes, path: str) -> dict[str, Any]:
    prefix = text[:2048].casefold()
    markers = [marker for marker in GENERATED_MARKERS if marker in prefix]
    if markers:
        raise AdmissionError(f"{path}: generated-code marker detected: {markers}")

    try:
        tree = ast.parse(text, filename=path)
        compile(text, path, "exec", dont_inherit=True, optimize=0)
    except SyntaxError as exc:
        raise AdmissionError(f"{path}: Python parse/compile failed: {exc}") from exc

    ast_nodes = sum(1 for _ in ast.walk(tree))
    defs = sum(isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) for node in ast.walk(tree))
    code_lines = 0
    comment_lines = 0
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            comment_lines += 1
        else:
            code_lines += 1

    if len(raw) < 4_000 or code_lines < 80 or ast_nodes < 150 or defs < 5:
        raise AdmissionError(
            f"{path}: substantive implementation threshold failed "
            f"bytes={len(raw)} code_lines={code_lines} ast_nodes={ast_nodes} defs={defs}"
        )

    return {
        "python_ast_valid": True,
        "python_compile_valid": True,
        "utf8_identity_valid": True,
        "size_bytes": len(raw),
        "code_lines": code_lines,
        "comment_lines": comment_lines,
        "ast_nodes": ast_nodes,
        "function_or_class_defs": defs,
        "generated_marker_hits": [],
    }


def token_shingles(text: str) -> set[tuple[str, ...]]:
    tokens = TOKEN_RE.findall(text.casefold())
    if len(tokens) < SHINGLE_SIZE:
        return set()
    return {tuple(tokens[i : i + SHINGLE_SIZE]) for i in range(len(tokens) - SHINGLE_SIZE + 1)}


def near_jaccard(left: str, right: str) -> float:
    a = token_shingles(left)
    b = token_shingles(right)
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def upstream_raw_url(commit: str, path: str, repository_url: str) -> str:
    slug = repository_url.removeprefix("https://github.com/").strip("/")
    return f"https://raw.githubusercontent.com/{slug}/{commit}/{path}"


def materialize_selected(cfg: dict[str, Any], output: Path) -> tuple[list[dict[str, Any]], list[tuple[str, str]]]:
    objects: list[dict[str, Any]] = []
    texts: list[tuple[str, str]] = []
    snapshot_dir = output / "snapshots"
    snapshot_dir.mkdir(parents=True, exist_ok=True)
    for item in cfg["files"]:
        path = item["path"]
        assert_path_allowed(path)
        raw_url = upstream_raw_url(cfg["upstream_commit"], path, cfg["repository_url"])
        raw = download(raw_url)
        if len(raw) != item["size_bytes"]:
            raise AdmissionError(f"{path}: byte-size drift")
        if git_blob_sha1(raw) != item["git_blob_sha1"]:
            raise AdmissionError(f"{path}: Git blob identity drift")
        try:
            text = raw.decode("utf-8", errors="strict")
        except UnicodeDecodeError as exc:
            raise AdmissionError(f"{path}: strict UTF-8 decode failed") from exc
        if text.encode("utf-8") != raw:
            raise AdmissionError(f"{path}: identity normalization failed")
        privacy = scan_secret_privacy(raw, text, path)
        quality = quality_and_parse(text, raw, path)
        raw_sha = sha256(raw)
        (snapshot_dir / f"{item['git_blob_sha1']}.py").write_bytes(raw)
        objects.append(
            {
                "path": path,
                "role": item["role"],
                "size_bytes": len(raw),
                "git_blob_sha1": item["git_blob_sha1"],
                "raw_sha256": raw_sha,
                "normalization_sha256": raw_sha,
                "normalization_policy": cfg["normalization_policy"],
                "raw_url": raw_url,
                "privacy_secret_scan": privacy,
                "quality": quality,
            }
        )
        texts.append((f"jinja:{path}", text))
    return objects, texts


def materialize_license(cfg: dict[str, Any], output: Path) -> dict[str, Any]:
    lic = cfg["license"]
    raw = download(lic["raw_url"], max_bytes=20_000)
    if len(raw) != lic["size_bytes"]:
        raise AdmissionError("license byte-size drift")
    if git_blob_sha1(raw) != lic["git_blob_sha1"]:
        raise AdmissionError("license Git blob identity drift")
    text = raw.decode("utf-8", errors="strict")
    required_phrases = (
        "Redistribution and use in source and binary forms",
        "with or without modification",
        "Neither the name of the copyright holder",
    )
    missing = [phrase for phrase in required_phrases if phrase not in text]
    if missing:
        raise AdmissionError(f"license grant text drift: {missing}")
    rights_dir = output / "rights-evidence"
    rights_dir.mkdir(parents=True, exist_ok=True)
    (rights_dir / "JINJA_LICENSE.txt").write_bytes(raw)
    return {
        "spdx": lic["spdx"],
        "git_blob_sha1": lic["git_blob_sha1"],
        "sha256": sha256(raw),
        "size_bytes": len(raw),
        "training_use_decision": lic["training_use_decision"],
        "redistribution_decision": lic["redistribution_decision"],
        "conditions": lic["conditions"],
        "required_grant_phrases_present": True,
    }


def incumbent_texts(cfg: dict[str, Any]) -> list[tuple[str, str, str]]:
    result: list[tuple[str, str, str]] = []
    for item in cfg["incumbent_code_families_for_dedup"]:
        repo_slug = item["source_family"].removeprefix("github:")
        url = f"https://raw.githubusercontent.com/{repo_slug}/{item['commit']}/{item['path']}"
        raw = download(url)
        if git_blob_sha1(raw) != item["git_blob_sha1"]:
            raise AdmissionError(f"incumbent identity drift: {item['source_family']} {item['path']}")
        text = raw.decode("utf-8", errors="strict")
        result.append((item["source_family"], item["path"], text))
    return result


def dedup_report(cfg: dict[str, Any], objects: list[dict[str, Any]], texts: list[tuple[str, str]]) -> dict[str, Any]:
    raw_sha = [item["raw_sha256"] for item in objects]
    blob_sha = [item["git_blob_sha1"] for item in objects]
    if len(raw_sha) != len(set(raw_sha)) or len(blob_sha) != len(set(blob_sha)):
        raise AdmissionError("exact duplicate inside selected Jinja object set")

    comparisons: list[dict[str, Any]] = []
    for i, (left_id, left_text) in enumerate(texts):
        for right_id, right_text in texts[i + 1 :]:
            score = near_jaccard(left_text, right_text)
            comparisons.append({"left": left_id, "right": right_id, "jaccard": score, "scope": "within_jinja"})
            if score >= NEAR_THRESHOLD:
                raise AdmissionError(f"near duplicate inside Jinja selection: {left_id} vs {right_id} = {score}")

    incumbents = incumbent_texts(cfg)
    for left_id, left_text in texts:
        for family, path, other_text in incumbents:
            score = near_jaccard(left_text, other_text)
            comparisons.append({"left": left_id, "right": f"{family}:{path}", "jaccard": score, "scope": "cross_source"})
            if score >= NEAR_THRESHOLD:
                raise AdmissionError(f"near duplicate against incumbent code: {left_id} vs {family}:{path} = {score}")

    return {
        "exact_duplicates": [],
        "near_threshold": NEAR_THRESHOLD,
        "comparisons": comparisons,
        "near_duplicate_pairs": [],
        "incumbent_families_checked": [item["source_family"] for item in cfg["incumbent_code_families_for_dedup"]],
    }


def build_report(repo: Path, output: Path) -> dict[str, Any]:
    cfg = load_config(repo)
    output.mkdir(parents=True, exist_ok=True)
    repository = verify_repository(cfg)
    license_evidence = materialize_license(cfg, output)
    objects, texts = materialize_selected(cfg, output)
    dedup = dedup_report(cfg, objects, texts)

    if any(item["size_bytes"] <= 0 for item in objects):
        raise AdmissionError("zero-byte capacity object")
    capacity = sum(item["size_bytes"] for item in objects)
    if capacity != cfg["capacity_bytes"]:
        raise AdmissionError("executed capacity differs from declared capacity")

    report: dict[str, Any] = {
        "schema_version": REPORT_SCHEMA,
        "worker_id": cfg["worker_id"],
        "authority": "EXTERNAL_REAL_CODE_SOURCE_ADMISSION",
        "execution_profile": "LOCAL_FREE",
        "verdict": "ADMIT",
        "source_id": cfg["source_id"],
        "source_family": cfg["source_family"],
        "independent_family_credit": 1,
        "upstream_commit": cfg["upstream_commit"],
        "repository": repository,
        "license": license_evidence,
        "purpose": cfg["purpose"],
        "training_purpose_decision": "ALLOWED",
        "redistribution_decision": "ALLOWED_WITH_LICENSE_CONDITIONS",
        "objects": objects,
        "object_count": len(objects),
        "capacity_bytes": capacity,
        "capacity_excludes_docs_tests_generated_vendored": True,
        "normalization_identity_preserved": True,
        "privacy_secrets_pass": True,
        "syntax_parse_compile_pass": True,
        "quality_pass": True,
        "dedup": dedup,
        "evaluation_reservation": {
            "initial_live_jinja_reservations": cfg["evaluation_boundary"]["current_jinja_reservations_observed_at_initial_check"],
            "final_live_recheck_required": True,
            "selected_objects_are_training_only_not_evaluation_reservations": True,
        },
        "family_identity": {
            "family": cfg["source_family"],
            "one_family_despite_five_files": True,
            "not_a_fork_or_mirror": True,
            "incumbent_distinct_families": [item["source_family"] for item in cfg["incumbent_code_families_for_dedup"]],
        },
        "claim_boundary": [
            "bounded five-file Jinja implementation snapshot only",
            "not the whole Jinja repository",
            "no docs/tests/examples/generated/packaging bytes counted as code capacity",
            "no evaluation-use authority granted",
            "no model training executed by this admission",
            "license conditions remain attached to redistribution of source snapshots"
        ],
    }
    report["authority_sha256"] = sha256(cjson(report))
    return report


def validate_report(report: dict[str, Any]) -> None:
    if report.get("schema_version") != REPORT_SCHEMA:
        raise AdmissionError("report schema mismatch")
    authority = report.get("authority_sha256")
    if not isinstance(authority, str) or len(authority) != 64:
        raise AdmissionError("missing authority identity")
    copy = dict(report)
    copy.pop("authority_sha256", None)
    if sha256(cjson(copy)) != authority:
        raise AdmissionError("authority self-hash mismatch")
    if report.get("verdict") != "ADMIT":
        raise AdmissionError("terminal report is not ADMIT")
    if report.get("object_count") != 5 or report.get("capacity_bytes") != 238695:
        raise AdmissionError("bounded object count/capacity mismatch")
    if report.get("source_family") != "github:pallets/jinja":
        raise AdmissionError("family mismatch")
    if not all(
        report.get(field) is True
        for field in (
            "capacity_excludes_docs_tests_generated_vendored",
            "normalization_identity_preserved",
            "privacy_secrets_pass",
            "syntax_parse_compile_pass",
            "quality_pass",
        )
    ):
        raise AdmissionError("one or more hard gates are not PASS")
    if report["dedup"]["exact_duplicates"] or report["dedup"]["near_duplicate_pairs"]:
        raise AdmissionError("dedup gate is not clean")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("run", "validate"))
    parser.add_argument("--repo", default=".")
    parser.add_argument("--output-dir", default="next100-047-evidence")
    parser.add_argument("--report")
    args = parser.parse_args()

    if args.command == "run":
        repo = Path(args.repo).resolve()
        output = Path(args.output_dir).resolve()
        report = build_report(repo, output)
        validate_report(report)
        report_path = output / "next100-047-jinja-code-admission.json"
        report_path.write_bytes(cjson(report))
        print(json.dumps(report, indent=2, ensure_ascii=False, sort_keys=True))
        return

    if not args.report:
        raise SystemExit("--report is required for validate")
    report = json.loads(Path(args.report).read_bytes())
    validate_report(report)
    print(report["authority_sha256"])


if __name__ == "__main__":
    main()
