#!/usr/bin/env python3
"""Exact bounded attrs source admission validator for NEXT100-053.

Stdlib-only, network-bounded, LOCAL_FREE. It acquires only pinned public GitHub
objects, verifies release/tag/tree/blob identities, preserves exact UTF-8 bytes,
parses Python, scans privacy/secrets, rejects generated/vendor capacity, and
checks exact/near dedup against the incumbent admitted code registry.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import ipaddress
import json
import re
import urllib.request
from pathlib import Path
from typing import Any

CONFIG = Path("configs/data/next100_053_attrs_code_source_v1.json")
CONFIG_SCHEMA = "12-6.next100-053-attrs-code-source.v1"
REPORT_SCHEMA = "12-6.next100-053-attrs-code-admission-report.v1"
USER_AGENT = "12-6-NEXT100-053-attrs-admission/1"
MAX_FILE_BYTES = 180_000
NEAR_THRESHOLD = 0.85
SHINGLE_SIZE = 5

SECRET_PATTERNS = (
    ("private_key", re.compile(rb"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----")),
    ("github_token", re.compile(rb"\bgh[pousr]_[A-Za-z0-9_]{20,}\b")),
    ("openai_key", re.compile(rb"\bsk-[A-Za-z0-9_-]{20,}\b")),
    ("aws_access_key", re.compile(rb"\bAKIA[0-9A-Z]{16}\b")),
    ("slack_token", re.compile(rb"\bxox[baprs]-[A-Za-z0-9-]{20,}\b")),
    ("npm_token", re.compile(rb"\bnpm_[A-Za-z0-9]{20,}\b")),
)
EMAIL_RE = re.compile(r"(?<![A-Za-z0-9._%+-])([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})(?![A-Za-z0-9._%+-])")
IPV4_RE = re.compile(r"(?<!\d)(?:\d{1,3}\.){3}\d{1,3}(?!\d)")
TOKEN_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*|\d+|[^\s]")
GENERATED_MARKERS = ("generated by", "auto-generated", "autogenerated", "do not edit")
BANNED_PARTS = {"vendor", "vendored", "third_party", "third-party", "node_modules", "dist", "build", "generated", "gen", "deps", "site-packages"}
SAFE_EMAIL_DOMAINS = {"example.com", "example.org", "example.net"}
MIT_REQUIRED_GRANT_PHRASES = (
    "Permission is hereby granted, free of charge, to any person obtaining a copy",
    "to deal in the Software without restriction",
    "use, copy, modify, merge, publish, distribute, sublicense, and/or sell",
    "The above copyright notice and this permission notice shall be included",
)


class AdmissionError(RuntimeError):
    pass


def cjson(value: object) -> bytes:
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n").encode("utf-8")


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def git_blob_sha1(data: bytes) -> str:
    return hashlib.sha1(f"blob {len(data)}\0".encode("ascii") + data).hexdigest()


def download(url: str, *, max_bytes: int = MAX_FILE_BYTES) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT, "Accept": "application/vnd.github+json"})
    with urllib.request.urlopen(req, timeout=30) as response:
        data = response.read(max_bytes + 1)
    if len(data) > max_bytes:
        raise AdmissionError(f"bounded download exceeded {max_bytes} bytes: {url}")
    return data


def json_download(url: str, *, max_bytes: int = 200_000) -> dict[str, Any]:
    value = json.loads(download(url, max_bytes=max_bytes))
    if not isinstance(value, dict):
        raise AdmissionError(f"expected JSON object: {url}")
    return value


def load_config(repo: Path) -> dict[str, Any]:
    cfg = json.loads((repo / CONFIG).read_bytes())
    if cfg.get("schema_version") != CONFIG_SCHEMA:
        raise AdmissionError("unsupported config schema")
    if cfg.get("worker_id") != "NEXT100-053-CODE-ATTRS":
        raise AdmissionError("worker identity drift")
    if cfg.get("execution_profile") != "LOCAL_FREE":
        raise AdmissionError("execution profile must remain LOCAL_FREE")
    if cfg.get("source_family") != "github:python-attrs/attrs":
        raise AdmissionError("unexpected source family")
    if len(cfg.get("files", [])) != 4:
        raise AdmissionError("bounded v1 authority requires exactly four files")
    if sum(item["size_bytes"] for item in cfg["files"]) != cfg["capacity_bytes"]:
        raise AdmissionError("declared capacity does not equal selected implementation bytes")
    return cfg


def verify_repository_and_release(cfg: dict[str, Any]) -> dict[str, Any]:
    meta = json_download("https://api.github.com/repos/python-attrs/attrs")
    if meta.get("html_url") != cfg["repository_url"]:
        raise AdmissionError("canonical repository identity drift")
    if meta.get("fork") is not False or meta.get("mirror_url") is not None:
        raise AdmissionError("fork/mirror cannot define the independent source family")

    ref = json_download(f"https://api.github.com/repos/python-attrs/attrs/git/ref/tags/{cfg['release_tag']}")
    obj = ref.get("object", {})
    if obj.get("type") != "tag" or obj.get("sha") != cfg["release_tag_object_sha1"]:
        raise AdmissionError("stable release tag object drift")

    tag = json_download(f"https://api.github.com/repos/python-attrs/attrs/git/tags/{cfg['release_tag_object_sha1']}")
    if tag.get("tag") != cfg["release_tag"]:
        raise AdmissionError("release tag name drift")
    if tag.get("object", {}).get("sha") != cfg["upstream_commit"]:
        raise AdmissionError("release tag no longer resolves to pinned commit")
    if tag.get("verification", {}).get("verified") is not True:
        raise AdmissionError("release tag verification is not valid")

    commit = json_download(f"https://api.github.com/repos/python-attrs/attrs/git/commits/{cfg['upstream_commit']}")
    if commit.get("tree", {}).get("sha") != cfg["upstream_tree"]:
        raise AdmissionError("upstream tree identity drift")
    if commit.get("verification", {}).get("verified") is not True:
        raise AdmissionError("pinned release commit verification is not valid")

    return {
        "html_url": meta.get("html_url"),
        "fork": meta.get("fork"),
        "mirror_url": meta.get("mirror_url"),
        "archived": meta.get("archived"),
        "release_tag": cfg["release_tag"],
        "release_tag_object_sha1": cfg["release_tag_object_sha1"],
        "release_tag_verified": True,
        "commit": cfg["upstream_commit"],
        "commit_verified": True,
        "tree": cfg["upstream_tree"],
    }


def upstream_raw_url(cfg: dict[str, Any], path: str) -> str:
    return f"https://raw.githubusercontent.com/python-attrs/attrs/{cfg['upstream_commit']}/{path}"


def validate_mit_grant_text(text: str) -> None:
    """Validate the pinned MIT grant independent of harmless line wrapping."""

    normalized = " ".join(text.split())
    missing = [phrase for phrase in MIT_REQUIRED_GRANT_PHRASES if phrase not in normalized]
    if missing:
        raise AdmissionError(f"MIT grant text drift: {missing}")


def verify_license_and_policy(cfg: dict[str, Any], output: Path) -> tuple[dict[str, Any], dict[str, Any]]:
    lic = cfg["license"]
    raw = download(lic["raw_url"], max_bytes=20_000)
    if len(raw) != lic["size_bytes"] or git_blob_sha1(raw) != lic["git_blob_sha1"]:
        raise AdmissionError("MIT license bytes/blob identity drift")
    text = raw.decode("utf-8", errors="strict")
    validate_mit_grant_text(text)

    rights_dir = output / "rights-evidence"
    rights_dir.mkdir(parents=True, exist_ok=True)
    (rights_dir / "ATTRS_LICENSE.txt").write_bytes(raw)

    policy_cfg = cfg["upstream_ai_policy"]
    policy_raw = download(upstream_raw_url(cfg, policy_cfg["path"]), max_bytes=20_000)
    if git_blob_sha1(policy_raw) != policy_cfg["git_blob_sha1"]:
        raise AdmissionError("upstream AI policy identity drift")
    policy_text = policy_raw.decode("utf-8", errors="strict")
    if "By submitting a pull request" not in policy_text or "you retain your copyright" not in policy_text:
        raise AdmissionError("AI policy scope text drift")
    (rights_dir / "ATTRS_AI_POLICY.md").write_bytes(policy_raw)

    return (
        {
            "spdx": "MIT",
            "git_blob_sha1": lic["git_blob_sha1"],
            "sha256": sha256(raw),
            "size_bytes": len(raw),
            "training_use_decision": lic["training_use_decision"],
            "redistribution_decision": lic["redistribution_decision"],
            "conditions": lic["conditions"],
            "required_grant_phrases_present": True,
        },
        {
            "path": policy_cfg["path"],
            "git_blob_sha1": policy_cfg["git_blob_sha1"],
            "sha256": sha256(policy_raw),
            "scope_decision": policy_cfg["scope_decision"],
            "does_not_override_mit_release_license": True,
        },
    )


def assert_path_allowed(path: str) -> None:
    p = Path(path)
    if p.suffix != ".py":
        raise AdmissionError(f"non-Python capacity path excluded: {path}")
    if not path.startswith("src/attr/"):
        raise AdmissionError(f"outside implementation root: {path}")
    if path.startswith("src/attrs/"):
        raise AdmissionError(f"public forwarding shim excluded from capacity: {path}")
    parts = {part.casefold() for part in p.parts}
    if parts & BANNED_PARTS:
        raise AdmissionError(f"vendored/generated/build path excluded: {path}")


def scan_secret_privacy(raw: bytes, text: str, path: str) -> dict[str, Any]:
    secret_hits = [name for name, pattern in SECRET_PATTERNS if pattern.search(raw)]
    if secret_hits:
        raise AdmissionError(f"{path}: secret-like material: {secret_hits}")

    emails = sorted(set(EMAIL_RE.findall(text)))
    unsafe_emails = [email for email in emails if email.rsplit("@", 1)[-1].casefold() not in SAFE_EMAIL_DOMAINS]
    if unsafe_emails:
        raise AdmissionError(f"{path}: non-example email-like material: {unsafe_emails}")

    private_ips: list[str] = []
    for candidate in sorted(set(IPV4_RE.findall(text))):
        try:
            ip = ipaddress.ip_address(candidate)
        except ValueError:
            continue
        if ip.is_private and not ip.is_loopback:
            private_ips.append(candidate)
    if private_ips:
        raise AdmissionError(f"{path}: private-network endpoint-like material: {private_ips}")

    return {
        "secret_hits": [],
        "email_like_count": len(emails),
        "non_example_email_count": 0,
        "private_ip_count": 0,
    }


def quality_and_parse(text: str, raw: bytes, path: str) -> dict[str, Any]:
    prefix = text[:2048].casefold()
    markers = [marker for marker in GENERATED_MARKERS if marker in prefix]
    if markers:
        raise AdmissionError(f"{path}: generated-code marker detected: {markers}")
    try:
        tree = ast.parse(text, filename=path)
        compile(text, path, "exec", dont_inherit=True, optimize=0)
    except SyntaxError as exc:
        raise AdmissionError(f"{path}: Python parse/compile failed: {exc}") from exc

    ast_nodes = sum(1 for _ in ast.walk(tree))
    defs = sum(isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) for node in ast.walk(tree))
    code_lines = 0
    comment_lines = 0
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            comment_lines += 1
        else:
            code_lines += 1
    if len(raw) < 4_000 or code_lines < 80 or ast_nodes < 150 or defs < 5:
        raise AdmissionError(
            f"{path}: substantive implementation threshold failed bytes={len(raw)} "
            f"code_lines={code_lines} ast_nodes={ast_nodes} defs={defs}"
        )
    return {
        "python_ast_valid": True,
        "python_compile_valid": True,
        "utf8_identity_valid": True,
        "size_bytes": len(raw),
        "code_lines": code_lines,
        "comment_lines": comment_lines,
        "ast_nodes": ast_nodes,
        "function_or_class_defs": defs,
        "generated_marker_hits": [],
    }


def materialize_selected(cfg: dict[str, Any], output: Path) -> tuple[list[dict[str, Any]], list[tuple[str, str]]]:
    objects: list[dict[str, Any]] = []
    texts: list[tuple[str, str]] = []
    snapshot_dir = output / "snapshots"
    snapshot_dir.mkdir(parents=True, exist_ok=True)
    for item in cfg["files"]:
        path = item["path"]
        assert_path_allowed(path)
        raw_url = upstream_raw_url(cfg, path)
        raw = download(raw_url)
        if len(raw) != item["size_bytes"]:
            raise AdmissionError(f"{path}: byte-size drift")
        if git_blob_sha1(raw) != item["git_blob_sha1"]:
            raise AdmissionError(f"{path}: Git blob identity drift")
        try:
            text = raw.decode("utf-8", errors="strict")
        except UnicodeDecodeError as exc:
            raise AdmissionError(f"{path}: strict UTF-8 decode failed") from exc
        if text.encode("utf-8") != raw:
            raise AdmissionError(f"{path}: identity normalization failed")
        privacy = scan_secret_privacy(raw, text, path)
        quality = quality_and_parse(text, raw, path)
        raw_sha = sha256(raw)
        (snapshot_dir / f"{item['git_blob_sha1']}.py").write_bytes(raw)
        objects.append({
            "path": path,
            "role": item["role"],
            "size_bytes": len(raw),
            "git_blob_sha1": item["git_blob_sha1"],
            "raw_sha256": raw_sha,
            "normalization_sha256": raw_sha,
            "normalization_policy": cfg["normalization_policy"],
            "raw_url": raw_url,
            "privacy_secret_scan": privacy,
            "quality": quality,
        })
        texts.append((f"attrs:{path}", text))
    return objects, texts


def token_shingles(text: str) -> set[tuple[str, ...]]:
    tokens = TOKEN_RE.findall(text.casefold())
    if len(tokens) < SHINGLE_SIZE:
        return set()
    return {tuple(tokens[i:i + SHINGLE_SIZE]) for i in range(len(tokens) - SHINGLE_SIZE + 1)}


def near_jaccard(left: str, right: str) -> float:
    a = token_shingles(left)
    b = token_shingles(right)
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def incumbent_texts(cfg: dict[str, Any]) -> list[tuple[str, str, str]]:
    result: list[tuple[str, str, str]] = []
    for item in cfg["incumbent_code_families_for_dedup"]:
        slug = item["source_family"].removeprefix("github:")
        url = f"https://raw.githubusercontent.com/{slug}/{item['commit']}/{item['path']}"
        raw = download(url)
        if git_blob_sha1(raw) != item["git_blob_sha1"]:
            raise AdmissionError(f"incumbent identity drift: {item['source_family']} {item['path']}")
        result.append((item["source_family"], item["path"], raw.decode("utf-8", errors="strict")))
    return result


def dedup_report(cfg: dict[str, Any], objects: list[dict[str, Any]], texts: list[tuple[str, str]]) -> dict[str, Any]:
    raw_sha = [item["raw_sha256"] for item in objects]
    blob_sha = [item["git_blob_sha1"] for item in objects]
    if len(raw_sha) != len(set(raw_sha)) or len(blob_sha) != len(set(blob_sha)):
        raise AdmissionError("exact duplicate inside selected attrs object set")

    comparisons: list[dict[str, Any]] = []
    for i, (left_id, left_text) in enumerate(texts):
        for right_id, right_text in texts[i + 1:]:
            score = near_jaccard(left_text, right_text)
            comparisons.append({"left": left_id, "right": right_id, "jaccard": score, "scope": "within_attrs"})
            if score >= NEAR_THRESHOLD:
                raise AdmissionError(f"near duplicate inside attrs selection: {left_id} vs {right_id} = {score}")

    incumbents = incumbent_texts(cfg)
    for left_id, left_text in texts:
        for family, path, other_text in incumbents:
            score = near_jaccard(left_text, other_text)
            comparisons.append({"left": left_id, "right": f"{family}:{path}", "jaccard": score, "scope": "cross_source"})
            if score >= NEAR_THRESHOLD:
                raise AdmissionError(f"near duplicate against incumbent code: {left_id} vs {family}:{path} = {score}")

    return {
        "exact_duplicates": [],
        "near_threshold": NEAR_THRESHOLD,
        "comparisons": comparisons,
        "near_duplicate_pairs": [],
        "incumbent_families_checked": [item["source_family"] for item in cfg["incumbent_code_families_for_dedup"]],
    }


def build_report(repo: Path, output: Path) -> dict[str, Any]:
    cfg = load_config(repo)
    output.mkdir(parents=True, exist_ok=True)
    repository = verify_repository_and_release(cfg)
    license_evidence, ai_policy = verify_license_and_policy(cfg, output)
    objects, texts = materialize_selected(cfg, output)
    dedup = dedup_report(cfg, objects, texts)
    capacity = sum(item["size_bytes"] for item in objects)
    if capacity != cfg["capacity_bytes"]:
        raise AdmissionError("executed capacity differs from declared capacity")

    report: dict[str, Any] = {
        "schema_version": REPORT_SCHEMA,
        "worker_id": cfg["worker_id"],
        "authority": "EXTERNAL_REAL_CODE_SOURCE_ADMISSION",
        "execution_profile": "LOCAL_FREE",
        "verdict": "ADMIT",
        "source_id": cfg["source_id"],
        "source_family": cfg["source_family"],
        "independent_family_credit": 1,
        "release_tag": cfg["release_tag"],
        "upstream_commit": cfg["upstream_commit"],
        "upstream_tree": cfg["upstream_tree"],
        "repository": repository,
        "license": license_evidence,
        "upstream_ai_policy": ai_policy,
        "purpose": cfg["purpose"],
        "training_purpose_decision": "ALLOWED",
        "redistribution_decision": "ALLOWED_WITH_LICENSE_CONDITIONS",
        "objects": objects,
        "object_count": len(objects),
        "capacity_bytes": capacity,
        "capacity_excludes_shims_stubs_docs_tests_generated_vendored": True,
        "normalization_identity_preserved": True,
        "privacy_secrets_pass": True,
        "syntax_parse_compile_pass": True,
        "quality_pass": True,
        "dedup": dedup,
        "evaluation_reservation": {
            "initial_registry_commit": cfg["evaluation_boundary"]["initial_registry_commit"],
            "initial_reserved_registry_blob": cfg["evaluation_boundary"]["initial_reserved_registry_blob"],
            "initial_reserved_set_count": cfg["evaluation_boundary"]["initial_reserved_set_count"],
            "initial_attrs_pr_hits": cfg["evaluation_boundary"]["initial_attrs_pr_hits"],
            "final_live_recheck_required_before_seal": True,
            "selected_objects_are_training_only_not_evaluation_authority": True,
        },
        "family_identity": {
            "family": cfg["source_family"],
            "one_family_despite_four_files": True,
            "not_a_fork_or_mirror": True,
            "incumbent_distinct_families": [item["source_family"] for item in cfg["incumbent_code_families_for_dedup"]],
        },
        "claim_boundary": [
            "bounded four-file attrs implementation snapshot only",
            "not the whole attrs repository",
            "src/attrs forwarding shims, stubs, docs, tests, benchmarks, examples, generated/build, packaging and lock bytes are not counted",
            "no evaluation-use authority granted",
            "no model training executed by this admission",
            "MIT notice condition remains attached to redistribution of source snapshots"
        ],
    }
    report["authority_sha256"] = sha256(cjson(report))
    return report


def validate_report(report: dict[str, Any]) -> None:
    if report.get("schema_version") != REPORT_SCHEMA:
        raise AdmissionError("report schema mismatch")
    authority = report.get("authority_sha256")
    if not isinstance(authority, str) or len(authority) != 64:
        raise AdmissionError("missing authority identity")
    copy = dict(report)
    copy.pop("authority_sha256", None)
    if sha256(cjson(copy)) != authority:
        raise AdmissionError("authority self-hash mismatch")
    if report.get("verdict") != "ADMIT":
        raise AdmissionError("terminal report is not ADMIT")
    if report.get("source_family") != "github:python-attrs/attrs":
        raise AdmissionError("family mismatch")
    if report.get("upstream_commit") != "7bfc49e9b22d5ba25b6e429524c3d49fee27cb36":
        raise AdmissionError("upstream commit mismatch")
    if report.get("object_count") != 4 or report.get("capacity_bytes") != 170435:
        raise AdmissionError("bounded object count/capacity mismatch")
    if not all(report.get(field) is True for field in (
        "capacity_excludes_shims_stubs_docs_tests_generated_vendored",
        "normalization_identity_preserved",
        "privacy_secrets_pass",
        "syntax_parse_compile_pass",
        "quality_pass",
    )):
        raise AdmissionError("one or more hard gates are not PASS")
    if report["dedup"]["exact_duplicates"] or report["dedup"]["near_duplicate_pairs"]:
        raise AdmissionError("dedup gate is not clean")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("run", "validate"))
    parser.add_argument("--repo", default=".")
    parser.add_argument("--output-dir", default="next100-053-evidence")
    parser.add_argument("--report")
    args = parser.parse_args()

    if args.command == "run":
        repo = Path(args.repo).resolve()
        output = Path(args.output_dir).resolve()
        report = build_report(repo, output)
        validate_report(report)
        report_path = output / "next100-053-attrs-code-admission.json"
        report_path.write_bytes(cjson(report))
        print(json.dumps(report, indent=2, ensure_ascii=False, sort_keys=True))
        return

    if not args.report:
        raise SystemExit("--report is required for validate")
    report = json.loads(Path(args.report).read_bytes())
    validate_report(report)
    print(report["authority_sha256"])


if __name__ == "__main__":
    main()