"""Post-Base-only architecture boundary.

Anything under this namespace is ineligible to become canonical Base evidence.
"""

from twelve_six.post_base.contract import (
    CANONICAL_BASE_EVIDENCE_NAMESPACE,
    CONTRACT_SCHEMA,
    POST_BASE_ARTIFACT_NAMESPACE,
    POST_BASE_EVIDENCE_NAMESPACE,
    CanonicalBasePolicy,
    DatasetProvenance,
    DialogueFormatLayer,
    DirectorySnapshot,
    EvaluationSeparation,
    FileIdentity,
    PostBaseConsumptionContract,
    PostBaseStage,
    PreparedPostBaseWorkspace,
    TokenizerCompatibility,
    prepare_post_base_workspace,
    snapshot_directory,
)
from twelve_six.post_base.sft_runner import (
    MAX_MECHANICS_STEPS,
    SFT_CHECKPOINT_NAMESPACE,
    SFT_EVALUATION_NAMESPACE,
    SFT_MECHANICS_SCHEMA,
    CheckpointGeneration,
    FixtureProvenance,
    FixtureSourceKind,
    MechanicsSplit,
    SFTCheckpointStore,
    SFTEvaluationStore,
    SFTExecutionMode,
    SFTMechanicsBackend,
    SFTMechanicsDataset,
    SFTMechanicsExample,
    SFTMechanicsPlan,
    SFTMechanicsReceipt,
    SFTStepReceipt,
    run_sft_mechanics,
)

__all__ = [
    "CANONICAL_BASE_EVIDENCE_NAMESPACE",
    "CONTRACT_SCHEMA",
    "MAX_MECHANICS_STEPS",
    "POST_BASE_ARTIFACT_NAMESPACE",
    "POST_BASE_EVIDENCE_NAMESPACE",
    "SFT_CHECKPOINT_NAMESPACE",
    "SFT_EVALUATION_NAMESPACE",
    "SFT_MECHANICS_SCHEMA",
    "CanonicalBasePolicy",
    "CheckpointGeneration",
    "DatasetProvenance",
    "DialogueFormatLayer",
    "DirectorySnapshot",
    "EvaluationSeparation",
    "FileIdentity",
    "FixtureProvenance",
    "FixtureSourceKind",
    "MechanicsSplit",
    "PostBaseConsumptionContract",
    "PostBaseStage",
    "PreparedPostBaseWorkspace",
    "SFTCheckpointStore",
    "SFTEvaluationStore",
    "SFTExecutionMode",
    "SFTMechanicsBackend",
    "SFTMechanicsDataset",
    "SFTMechanicsExample",
    "SFTMechanicsPlan",
    "SFTMechanicsReceipt",
    "SFTStepReceipt",
    "TokenizerCompatibility",
    "prepare_post_base_workspace",
    "run_sft_mechanics",
    "snapshot_directory",
]
